<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;
use App\Models\ReceivingLocation;

class ReceivingLocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $locations = [
            [
            'code'           => 'CORP-001',
            'name'           => 'Oficinas Corporativas Juárez',
            'type'           => 'corporate',
            'address'        => 'Av. Rafael Pérez Serna No. 755',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32410',
            'phone'          => '6562896600',
            'email'          => 'comunicacionmkt@totalgas.com',
            'manager_name'   => 'Julio César Salazar',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Oficinas centrales - Recepción en piso 1',
            ],[
            'code'           => 'E01149',
            'name'           => '[E01149] Lerdo',
            'type'           => 'service_station',
            'address'        => 'C. Ignacio Mejia 317, Col. Centro',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32160',
            'phone'          => '6562896600',
            'email'          => 'es1149_Lerdo@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V.(LERDO)',
            ],[
            'code'           => 'E01376',
            'name'           => '[E01376] Delicias',
            'type'           => 'service_station',
            'address'        => 'Blvd. Oscar Flores Sanchez 514, Col. Centro',
            'city'           => 'Delicias',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '33000',
            'phone'          => '6562896600',
            'email'          => 'es_1376delicias@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'SERVICIO SYC S.A. DE C.V. (DELICIAS)',
            ],[
            'code'           => 'E02172',
            'name'           => '[E02172] Parral',
            'type'           => 'service_station',
            'address'        => 'Av. Tecnológico 29, Col. Tecnológico',
            'city'           => 'Hidalgo del Parral',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '33850',
            'phone'          => '6562896600',
            'email'          => 'es2172_parral@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (PARRAL)',
            ],[
            'code'           => 'E02526',
            'name'           => '[E02526] Lopez Mateos',
            'type'           => 'service_station',
            'address'        => 'Av. Adolfo López Mateos 1604, Col. Melchor Ocampo',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32380',
            'phone'          => '6562896600',
            'email'          => 'es2526_LopezMateos@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (LOPEZ MATEOS)',
            ],[
            'code'           => 'E04179',
            'name'           => '[E04179] Gemela Chica',
            'type'           => 'service_station',
            'address'        => 'Av. Rafael Pérez Serna 676, Col. Partido Romero',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32330',
            'phone'          => '6562896600',
            'email'          => 'es4179_GemelaChica@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (GEMELA CHICA)',
            ],[
            'code'           => 'E04188',
            'name'           => '[E04188] Gemela Grande',
            'type'           => 'service_station',
            'address'        => 'Av. Rafael Pérez Serna 755, Col. Partido Romero',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32030',
            'phone'          => '6562896600',
            'email'          => 'es4188_GemelaGrande@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (GEMELA GRANDE)',
            ],[
            'code'           => 'E05170',
            'name'           => '[E05170] Plutarco',
            'type'           => 'service_station',
            'address'        => 'Av. Plutarco Elias Calles 2260, Fracc. Partido Iglesias',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32528',
            'phone'          => '6562896600',
            'email'          => 'es5170_plutarco@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'ESTACION CUSTODIA S.A. DE C.V. (PLUTARCO)',
            ],[
            'code'           => 'E05317',
            'name'           => '[E05317] Municipio Libre',
            'type'           => 'service_station',
            'address'        => 'Av. Municipio Libre No. 88 y Esq. Libertad, Col. Adición Sur',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32000',
            'phone'          => '6562896600',
            'email'          => 'es5317_MunicipioLibre@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (MUNICIPIO LIBRE)',
            ],[
            'code'           => 'E05465',
            'name'           => '[E05465] Aztecas',
            'type'           => 'service_station',
            'address'        => 'Av. De Los Aztecas 7821, José María Morelos',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32670',
            'phone'          => '6562896600',
            'email'          => 'es5465_Aztecas@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (AZTECAS)',
            ],[
            'code'           => 'E06410',
            'name'           => '[E06410] Misiones',
            'type'           => 'service_station',
            'address'        => 'Av. Paseo De La Victoria 4420 Col. Bosques Del Sol',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32617',
            'phone'          => '6562896600',
            'email'          => 'es6410_Misiones@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (MISIONES)',
            ],[
            'code'           => 'E06947',
            'name'           => '[E06947] Puerto de Palos',
            'type'           => 'service_station',
            'address'        => 'Av. Puerto de Palos 1050 Col. Tierra Nueva',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32300',
            'phone'          => '6562896600',
            'email'          => 'es6947_PuertoPalos@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (PUERTO DE PALOS)',
            ],[
            'code'           => 'E07167',
            'name'           => '[E07167] Miguel de la Madrid',
            'type'           => 'service_station',
            'address'        => 'Av. Miguel De La Madrid 7675 Col. Heroes De La Revolución',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32696',
            'phone'          => '6562896600',
            'email'          => 'es7167_miguelmadrid@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (MIGUEL DE LA MADRID)',
            ],[
            'code'           => 'E08244',
            'name'           => '[E08244] Permuta',
            'type'           => 'service_station',
            'address'        => 'Av. Manuel Talamas Camandari 850 Col. Manuel Gomez, Morin',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32575',
            'phone'          => '6562896600',
            'email'          => 'es8244_Permuta@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (PERMUTA)',
            ],[
            'code'           => 'E09191',
            'name'           => '[E09191] Electrolux',
            'type'           => 'service_station',
            'address'        => 'Av. Paseo Del Sur 105, Col. Fracc. Parajes Del Sur',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32030',
            'phone'          => '6562896600',
            'email'          => 'es9191_Electrolux@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (ELECTROLUX)',
            ],[
            'code'           => 'E09235',
            'name'           => '[E09235] Aeronáutica',
            'type'           => 'service_station',
            'address'        => 'Av. Aeronáutica 7023, Fraccionamiento Jardines del Aeropuerto',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32695',
            'phone'          => '6562896600',
            'email'          => 'es9235_Aeronautica@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (AERONAUTICA)',
            ],[
            'code'           => 'E09885',
            'name'           => '[E09885] Custodia',
            'type'           => 'service_station',
            'address'        => 'Av. Custodia de la República 1015, Fray Garcia de San Francisco',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32575',
            'phone'          => '6562896600',
            'email'          => 'es9885_Custodia@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (CUSTODIA)',
            ],[
            'code'           => 'E09893',
            'name'           => '[E09893] Anapra',
            'type'           => 'service_station',
            'address'        => 'Blvd. Bernardo Norzagaray 7270, Felipe Ángeles',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32100',
            'phone'          => '6562896600',
            'email'          => 'es9893_Anapra@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (ANAPRA)',
            ],[
            'code'           => 'E11007',
            'name'           => '[E11007] Aguascalientes',
            'type'           => 'service_station',
            'address'        => 'Av. Independencia 1839-D, Col. Trojes De Alonso',
            'city'           => 'Aguascalientes',
            'state'          => 'Aguascalientes',
            'country'        => 'México',
            'postal_code'    => '20116',
            'phone'          => '6562896600',
            'email'          => 'es11007_Independencia@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'ESTACION CUSTODIA S.A. DE C.V. (AGUASCALIENTES)',
            ],[
            'code'           => 'E01163',
            'name'           => '[E01163] Tecnológico',
            'type'           => 'service_station',
            'address'        => 'Carretera Panamericana 3130, Col. Del Marquez',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32610',
            'phone'          => '6562896600',
            'email'          => 'es1163_tecnologico@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (TECNOLOGICO)',
            ],[
            'code'           => 'P12841',
            'name'           => '[P12841] Ejército Nacional',
            'type'           => 'service_station',
            'address'        => 'Av. Ejercito Nacional 10151, Colonia Partido Senecu',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32459',
            'phone'          => '6562896600',
            'email'          => 'es9733_ejercito@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Distribuidora Gaso Mex S.A. de C.V (EJERCITO NAL)',
            ],[
            'code'           => 'P12840',
            'name'           => '[P12840] Satélite',
            'type'           => 'service_station',
            'address'        => 'Carretera Juárez Porvenir 1725, Colonia Fidel Avila Satelite',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32540',
            'phone'          => '6562896600',
            'email'          => 'es4457_satelite@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Distribuidora Gaso Mex S.A. de C.V. (SATELITE)',
            ],[
            'code'           => 'P13074',
            'name'           => '[P13074] Las Fuentes',
            'type'           => 'service_station',
            'address'        => 'Av. Paseo Triunfo de la República 394, Col. Partido Doblado',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32320',
            'phone'          => '6562896600',
            'email'          => 'es1159_fuentes@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Distribuidora Gaso Mex S.A. de C.V. (LAS FUENTES)',
            ],[
            'code'           => 'P13620',
            'name'           => '[P13620] Clara',
            'type'           => 'service_station',
            'address'        => 'Av. Paseo Triunfo de la República 935, Partido Manuel Doblado',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32409',
            'phone'          => '6562896600',
            'email'          => 'es1156_clara@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Distribuidora Clara S.A. de C.V. (CLARA)',
            ],[
            'code'           => 'P12842',
            'name'           => '[P12842] Solis',
            'type'           => 'service_station',
            'address'        => 'Ave. Leonardo Solis Barraza 2205, Colonia Senderos de San Isidro',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32575',
            'phone'          => '6562896600',
            'email'          => 'es10141_solis@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Distribuidora Gaso Mex S.A. de C.V. (SOLIS)',
            ],[
            'code'           => 'P12843',
            'name'           => '[P12843] Santiago Troncoso',
            'type'           => 'service_station',
            'address'        => 'Av. Santiago Troncoso 1701, Colonia Villa Bonita',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32550',
            'phone'          => '6562896600',
            'email'          => 'es12097_santiago@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Distribuidora Gaso Mex S.A. de C.V. (SANTIAGO TRO)',
            ],[
            'code'           => 'P13624',
            'name'           => '[P13624] Jarudo',
            'type'           => 'service_station',
            'address'        => 'Carretera Casas Grandes 3845, Col. Casas Grandes',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32630',
            'phone'          => '6562896600',
            'email'          => 'es1148_jarudo@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Servicio el Jarudo S.A. de C.V. (JARUDO)',
            ],[
            'code'           => 'E23214',
            'name'           => '[E23214] Hermanos Escobar',
            'type'           => 'service_station',
            'address'        => 'Av. Hermanos Escobar 3204, Col. La Playa',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32317',
            'phone'          => '6562896600',
            'email'          => 'es23214_hnosescobar@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (HERMANOS ESCOBAR)',
            ],[
            'code'           => 'E01242',
            'name'           => '[E01242] Villa Ahumada',
            'type'           => 'service_station',
            'address'        => 'Av. Miguel Ahumada Norte S/N',
            'city'           => 'Villa Ahumada',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32800',
            'phone'          => '6562896600',
            'email'          => 'es1242_villaahumada@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (VILLA AHUMADA)',
        ],[
            'code'           => 'P19190',
            'name'           => '[P19190] El Castaño',
            'type'           => 'service_station',
            'address'        => 'Av. Convención de 1914 Pte. 1125, Las Torres',
            'city'           => 'Aguascalientes',
            'state'          => 'Aguascalientes',
            'country'        => 'México',
            'postal_code'    => '20229',
            'phone'          => '6562896600',
            'email'          => 'es12900_elcastano@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'Servicios Gasolineros El Castaño SA de CV',
        ],[
            'code'           => 'P24938',
            'name'           => '[P24938] Travel Center',
            'type'           => 'service_station',
            'address'        => 'Carr. Panamericana No. 331',
            'city'           => 'Ciudad Juárez',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32370',
            'phone'          => '6562896600',
            'email'          => 'es24938_travelcenter@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (TRAVEL CENTER)',
        ],[
            'code'           => 'P24499',
            'name'           => '[P24499] Picachos',
            'type'           => 'service_station',
            'address'        => 'Carretera San Miguel de Allende a Queretaro, Km. 1.00, Col. San Jose de la Posta',
            'city'           => 'San Miguel de Allende',
            'state'          => 'Guanajuato',
            'country'        => 'México',
            'postal_code'    => '37780',
            'phone'          => '6562896600',
            'email'          => 'es24499_picachos@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'SMA PICACHOS S.A. DE C.V.',
        ],[
            'code'           => 'P24500',
            'name'           => '[P24500] Ventanas',
            'type'           => 'service_station',
            'address'        => 'Carretera San Miguel de Allende a Dolores Hidalgo, Km. 2 y 2.5, Col. Club de Golf Ventanas',
            'city'           => 'San Miguel de Allende',
            'state'          => 'Guanajuato',
            'country'        => 'México',
            'postal_code'    => '37718',
            'phone'          => '6562896600',
            'email'          => 'es24500_ventanas@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'SMA VENTANAS S.A. DE C.V.',
        ],[
            'code'           => 'P14946',
            'name'           => '[P14946] San Rafael',
            'type'           => 'service_station',
            'address'        => 'Av. Concepción Pte #1506, Col. Olivares Santana',
            'city'           => 'Aguascalientes',
            'state'          => 'Aguascalientes',
            'country'        => 'México',
            'postal_code'    => '20010',
            'phone'          => '6562896600',
            'email'          => 'es14946_sanrafael@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'GRUPO OPERADOR GASOLINERO TSA DEL CENTRO (SAN RAFAEL)',
        ],[
            'code'           => 'P15071',
            'name'           => '[P15071] Puertecito',
            'type'           => 'service_station',
            'address'        => 'Av. 16 de septiembre #18A, Col. Puertecito de la Virgen',
            'city'           => 'San Francisco de los Romo',
            'state'          => 'Aguascalientes',
            'country'        => 'México',
            'postal_code'    => '20320',
            'phone'          => '6562896600',
            'email'          => 'es15071_puertecito@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'GRUPO OPERADOR GASOLINERO TSA DEL CENTRO (PUERTECITO)',
        ],[
            'code'           => 'E15091',
            'name'           => '[E15091] Jesus Maria',
            'type'           => 'service_station',
            'address'        => 'Paseo de los Chicahuales 196',
            'city'           => 'Aguascalientes',
            'state'          => 'Aguascalientes',
            'country'        => 'México',
            'postal_code'    => '20924',
            'phone'          => '6562896600',
            'email'          => 'es15091_jesusmaria@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'GRUPO OPERADOR GASOLINERO TSA DEL CENTRO (JESUS MARIA)',
        ],[
            'code'           => 'P03340',
            'name'           => '[P03340] Gabriela Mistral',
            'type'           => 'service_station',
            'address'        => 'C. Gabriela Mistral #100, Col. La Estrella',
            'city'           => 'Aguascalientes',
            'state'          => 'Aguascalientes',
            'country'        => 'México',
            'postal_code'    => '20150',
            'phone'          => '6562896600',
            'email'          => 'es3340_gabrielamistral@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'FormulaGas',
        ],[
            'code'           => 'P10702',
            'name'           => '[P10702] Praxedis',
            'type'           => 'service_station',
            'address'        => 'Praxedis G. Guerrero',
            'city'           => 'Praxedis G. Guerrero',
            'state'          => 'Chihuahua',
            'country'        => 'México',
            'postal_code'    => '32550',
            'phone'          => '6562896600',
            'email'          => 'es10702_praxedis@totalgas.com',
            'manager_name'   => 'Jonathan Gomez',
            'is_active'      => true,
            'portal_blocked' => false,
            'notes'          => 'DIAZ GAS S.A. DE C.V. (Praxedis)',
        ]
        ];

        // 1. Agregamos los timestamps a cada elemento (insert() no los agrega automáticamente como create())
        $companyByLocationCode = [
            'CORP-001' => 'DGA',
            'E01149' => 'DGA',
            'E01163' => 'DGA',
            'E02172' => 'DGA',
            'E02526' => 'DGA',
            'E04179' => 'DGA',
            'E04188' => 'DGA',
            'E05317' => 'DGA',
            'E05465' => 'DGA',
            'E06410' => 'DGA',
            'E06947' => 'DGA',
            'E07167' => 'DGA',
            'E08244' => 'DGA',
            'E09191' => 'DGA',
            'E09235' => 'DGA',
            'E09885' => 'DGA',
            'E09893' => 'DGA',
            'E23214' => 'DGA',
            'P10702' => 'DGA',
            'P24938' => 'DGA',
            'E01242' => 'GVA',
            'E01376' => 'SSY',
            'E05170' => 'ECU',
            'E11007' => 'ECU',
            'P12840' => 'DGM',
            'P12841' => 'DGM',
            'P12842' => 'DGM',
            'P12843' => 'DGM',
            'P13074' => 'DGM',
            'P13620' => 'DCL',
            'P13624' => 'SJA',
            'E15091' => 'GOG',
            'P14946' => 'GOG',
            'P15071' => 'GOG',
            'P03340' => 'FGA',
            'P19190' => 'SGC',
            'P24499' => 'SPI',
            'P24500' => 'SVE',
        ];

        $companyIds = Company::whereIn('code', array_values(array_unique($companyByLocationCode)))
            ->pluck('id', 'code');

        $now = now();
        $insertData = array_map(function ($location) use ($now, $companyByLocationCode, $companyIds) {
            $companyCode = $companyByLocationCode[$location['code']] ?? null;

            return array_merge($location, [
                'company_id' => $companyCode ? $companyIds[$companyCode] ?? null : null,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }, $locations);

        // 2. Insertamos todo en la base de datos de forma masiva
        // Usamos chunk() como buena práctica por si la lista crece a cientos de estaciones en el futuro
        foreach ($insertData as $location) {
            ReceivingLocation::updateOrCreate(
                ['code' => $location['code']],
                $location
            );
        }
    }
}
