<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Station;

class StationSeeder extends Seeder
{
    public function run(): void
    {
        $stations = [
            [
                'company_id' => 1,
                'station_name' => 'Gemela Grande',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Rafael Pérez Serna 755, Col. Partido Romero, C.P. 32030',
                'expedition_place' => '32030',
                'server_ip' => '192.168.7.101',
                'database_name' => 'SG12_41882020',
                'cre_permit' => 'PL/19422/EXP/ES/2016',
                'email' => 'es4188_GemelaGrande@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '2',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 4,
                'station_name' => 'Aguascalientes',
                'country' => 'México',
                'state' => 'Aguascalientes',
                'municipality' => 'Aguascalientes',
                'address' => 'Av. Independecnia 1839-D, Col. Trojes De Alonso, C.P. 20116',
                'expedition_place' => '20116',
                'server_ip' => '192.168.28.101',
                'database_name' => 'SG12_11007+2020',
                'cre_permit' => 'PL/11393/EXP/ES/2015',
                'email' => 'es11007_Independencia@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '3',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Lerdo',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'C. Ignacio Mejia 317, Col. Centro, C.P. 32160',
                'expedition_place' => '32330',
                'server_ip' => '192.168.2.101',
                'database_name' => 'SG12_114912020',
                'cre_permit' => 'PL/748/EXP/ES/2015',
                'email' => 'es1149_Lerdo@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '5',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Lopez Mateos',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Adolfo López Mateos 1604, Col. Melchor Ocampo, C.P. 32380',
                'expedition_place' => '32330',
                'server_ip' => '192.168.5.101',
                'database_name' => 'SG12_25262020',
                'cre_permit' => 'PL/760/EXP/ES/2015',
                'email' => 'es2526_LopezMateos@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '6',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Gemela Chica',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Rafael Pérez Serna 676, Col. Partido Romero, C.P. 32330',
                'expedition_place' => '32330',
                'server_ip' => '192.168.6.101',
                'database_name' => 'SG12_4179_20',
                'cre_permit' => 'PL/761/EXP/ES/2015',
                'email' => 'es4179_GemelaChica@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '7',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Municipio Libre',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Municipio Libre No. 88 y Esq. Libertad, Col. Adición Sur, C.P. 32000',
                'expedition_place' => '32330',
                'server_ip' => '192.168.9.101',
                'database_name' => 'SG12_53172020',
                'cre_permit' => 'PL/776/EXP/ES/2015',
                'email' => 'es5317_MunicipioLibre@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '8',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Aztecas',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. De Los Aztecas 7821, José María Morelos, C.P. 32670',
                'expedition_place' => '32330',
                'server_ip' => '192.168.10.101',
                'database_name' => 'SG12_5465',
                'cre_permit' => 'PL/9938/EXP/ES/2015',
                'email' => 'es5465_Aztecas@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '9',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Misiones',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Paseo De La Victoria 4420 Col. Bosques Del Sol, C.P. 32617',
                'expedition_place' => '32330',
                'server_ip' => '192.168.11.101',
                'database_name' => 'SG12_6410',
                'cre_permit' => 'PL/775/EXP/ES/2015',
                'email' => 'es6410_Misiones@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '10',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Puerto de palos',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Puerto de Palos 1050 Col. Tierra Nueva, C.P. 32300',
                'expedition_place' => '32330',
                'server_ip' => '192.168.19.101',
                'database_name' => 'SG12_6947_2020',
                'cre_permit' => 'PL/790/EXP/ES/2015',
                'email' => 'es6947_PuertoPalos@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '11',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Miguel de la madrid',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Miguel De La Madrid 7675 Col. Heroes De La Revolución, C.P. 32696',
                'expedition_place' => '32330',
                'server_ip' => '192.168.13.101',
                'database_name' => 'CG_7167',
                'cre_permit' => 'PL/793/EXP/ES/2015',
                'email' => 'es7167_miguelmadrid@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '12',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Permuta',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Manuel Talamas Camandari 850 Col. Manuel Gomez, Morin, C.P. 32575',
                'expedition_place' => '32330',
                'server_ip' => '192.168.14.101',
                'database_name' => 'SG12_8244',
                'cre_permit' => 'PL/794/EXP/ES/2015',
                'email' => 'es8244_Permuta@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '13',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Electrolux',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Paseo Del Sur 105, Col. Fracc. Parajes Del Sur, C.P. 32030',
                'expedition_place' => '32330',
                'server_ip' => '192.168.15.101',
                'database_name' => 'SG12_9191',
                'cre_permit' => 'PL/9941/EXP/ES/2015',
                'email' => 'es9191_Electrolux@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '14',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Aeronáutica',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Aeronáutica 7023, Fraccionamiento Jardines del Aeropuerto, C.P. 32695',
                'expedition_place' => '32330',
                'server_ip' => '192.168.16.101',
                'database_name' => 'SG12_92352020',
                'cre_permit' => 'PL/19424/EXP/ES/2016',
                'email' => 'es9235_Aeronautica@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '15',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Custodia',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Custodia de la República 1015, Fray Garcia de San Francisco, C.P. 32575',
                'expedition_place' => '32330',
                'server_ip' => '192.168.17.101',
                'database_name' => 'SG12_98852020',
                'cre_permit' => 'PL/19423/EXP/ES/2016',
                'email' => 'es9885_Custodia@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '16',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Anapra',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Blvd. Bernardo Norzagaray 7270, Felipe Ángeles, C.P. 32100',
                'expedition_place' => '32330',
                'server_ip' => '192.168.18.101',
                'database_name' => 'SG12_9893',
                'cre_permit' => 'PL/20039/EXP/ES/2017',
                'email' => 'es9893_Anapra@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '17',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Parral',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Hidalgo del Parral',
                'address' => 'Av. Tecnológico 29, Col. Tecnológico, C.P. 33850',
                'expedition_place' => '32330',
                'server_ip' => '192.168.4.101',
                'database_name' => 'sg2172',
                'cre_permit' => 'PL/4201/EXP/ES/2015',
                'email' => 'es2172_parral@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '18',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 10,
                'station_name' => 'Delicias',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Delicias',
                'address' => 'Blvd. Oscar Flores Sanchez 514, Col. Centro, C.P. 33000',
                'expedition_place' => '33000',
                'server_ip' => '192.168.3.101',
                'database_name' => 'CG_1376',
                'cre_permit' => 'PL/10059/EXP/ES/2015',
                'email' => 'es_1376delicias@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '19',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 4,
                'station_name' => 'Plutarco',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Plutarco Elias Calles  2260, Fracc. Partido Iglesias, C.P. 32528',
                'expedition_place' => '32390',
                'server_ip' => '192.168.8.101',
                'database_name' => 'Custodia5170',
                'cre_permit' => 'PL/2060/EXP/ES/2015',
                'email' => 'es5170_plutarco@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '21',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Tecnológico',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Carretera Panamericana 3130, Col. Del Marquez, C.P. 32610',
                'expedition_place' => '32610',
                'server_ip' => '192.168.30.101',
                'database_name' => 'CG_1163',
                'cre_permit' => 'PL/9444/EXP/ES/2015',
                'email' => 'es1163_tecnologico@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '22',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 3,
                'station_name' => 'Ejército Nacional',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Ejercito Nacional 10151, Colonia Partido Senecú, C.P. 32459',
                'expedition_place' => '32543',
                'server_ip' => '192.168.21.101',
                'database_name' => 'CG_9733',
                'cre_permit' => 'PL/12841/EXP/ES/2015',
                'email' => 'es9733_ejercito@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '23',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 3,
                'station_name' => 'Satélite',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Carretera Juárez Porvenir 1725, Colonia Fidel Avila Satelite, C.P. 32540',
                'expedition_place' => '32540',
                'server_ip' => '192.168.22.101',
                'database_name' => 'CG_4457',
                'cre_permit' => 'PL/12840/EXP/ES/2015',
                'email' => 'es4457_satelite@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '24',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 3,
                'station_name' => 'Las fuentes',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Paseo Triunfo de la República 394, Col. Partido Doblado, C.P. 32320',
                'expedition_place' => '32320',
                'server_ip' => '192.168.23.101',
                'database_name' => 'cg_1159',
                'cre_permit' => 'PL/13074/EXP/ES/2016',
                'email' => 'es1159_fuentes@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '25',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'station_name' => 'Clara',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Paseo Triunfo de la República 935, Partido Manuel Doblado, C.P. 32409',
                'expedition_place' => '32320',
                'server_ip' => '192.168.24.101',
                'database_name' => 'CG_1156',
                'cre_permit' => 'PL/13620/EXP/ES/2016',
                'email' => 'es1156_clara@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '26',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 3,
                'station_name' => 'Solis',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Ave. Leonardo Solis Barraza 2205, Colonia Senderos de San Isidro, C.P. 32575',
                'expedition_place' => '32000',
                'server_ip' => '192.168.25.101',
                'database_name' => 'CG_10141',
                'cre_permit' => 'PL/12842/EXP/ES/2015',
                'email' => 'es10141_solis@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '27',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 3,
                'station_name' => 'Santiago Troncoso',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Santiago Troncoso 1701, Colonia Villa Bonita, C.P. 32550',
                'expedition_place' => '32550',
                'server_ip' => '192.168.26.101',
                'database_name' => 'SG12_12097',
                'cre_permit' => 'PL/12843/EXP/ES/2015',
                'email' => 'es12097_santiago@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '28',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 9,
                'station_name' => 'Jarudo',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Carretera Casas Grandes 3845, Col. Casas, C.P. 32630',
                'expedition_place' => '32630',
                'server_ip' => '192.168.27.101',
                'database_name' => 'CG_1148',
                'cre_permit' => 'PL/13624/EXP/ES/2016',
                'email' => 'es1148_jarudo@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '29',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Hermanos Escobar',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'Av. Hermanos Escobar 3204, Col. La Playa, C.P. 32317',
                'expedition_place' => '32330',
                'server_ip' => '192.168.29.101',
                'database_name' => 'CG_23214',
                'cre_permit' => 'PL/23214/EXP/ES/2020',
                'email' => 'es23214_hnosescobar@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '30',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 6,
                'station_name' => 'Villa Ahumada',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Villa Ahumada',
                'address' => 'Av. Miguel Ahumada Norte N S/N, C.P. 32800',
                'expedition_place' => '32330',
                'server_ip' => '192.168.32.101',
                'database_name' => 'CG_1242',
                'cre_permit' => 'PL/5114/EXP/ES/2015',
                'email' => 'es1242_villaahumada@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '31',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 11,
                'station_name' => 'El castaño',
                'country' => 'México',
                'state' => 'Aguascalientes',
                'municipality' => 'Aguascalientes',
                'address' => 'Av. Convención de 1914 Pte. 1125, Las Torres, C.P. 20229',
                'expedition_place' => '20229',
                'server_ip' => '192.168.33.101',
                'database_name' => 'CG_19190',
                'cre_permit' => 'PL/19190/EXP/ES/2016',
                'email' => 'es12900_elcastano@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '32',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Travel Center',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Juárez',
                'address' => 'CARR. PANAMERICANA No. 331',
                'expedition_place' => '32370',
                'server_ip' => '192.168.31.101',
                'database_name' => 'CG_24938',
                'cre_permit' => 'PL/24938/EXP/ES/2023',
                'email' => 'es24938_travelcenter@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '33',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 12,
                'station_name' => 'Picachos',
                'country' => 'México',
                'state' => 'Guanajuato',
                'municipality' => 'San Miguel de Allende',
                'address' => 'Carretera San Miguel de Allende a Queretaro, Kilometro 1.00, Col. San Jose de la Posta, C.P. 37780',
                'expedition_place' => '37780',
                'server_ip' => '192.168.34.101',
                'database_name' => 'CG_24499',
                'cre_permit' => 'PL/24499/EXP/ES/2022',
                'email' => 'es24499_picachos@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '34',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 13,
                'station_name' => 'Ventanas',
                'country' => 'México',
                'state' => 'Guanajuato',
                'municipality' => 'San Miguel de Allende',
                'address' => 'Carretera San Miguel de Allende a Dolores Hidalgo, Km. 2 y 2.5, Col. Club de Golf Ventanas, C.P. 37718',
                'expedition_place' => '37718',
                'server_ip' => '192.168.35.101',
                'database_name' => 'CG_24500',
                'cre_permit' => 'PL/24500/EXP/ES/2022',
                'email' => 'es24500_ventanas@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '35',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 7,
                'station_name' => 'San Rafael',
                'country' => 'México',
                'state' => 'Aguascalientes',
                'municipality' => 'Aguascalientes',
                'address' => 'Av. Concención Pte #1506, Col. Olivares Santana, CP 20010',
                'expedition_place' => '20010',
                'server_ip' => '192.168.36.101',
                'database_name' => 'CG_14946',
                'cre_permit' => 'PL/24816/EXP/ES/2023',
                'email' => 'es14946_sanrafael@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '36',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 7,
                'station_name' => 'Puertecito',
                'country' => 'México',
                'state' => 'Aguascalientes',
                'municipality' => 'San Francisco de los romo',
                'address' => 'Av. 16 de septiembre #18A, Col. Puertecito de la virgen, CP. 20320',
                'expedition_place' => null,
                'server_ip' => '192.168.37.101',
                'database_name' => 'CG_15071',
                'cre_permit' => 'PL/25627/EXP/ES/2024',
                'email' => 'es15071_puertecito@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '37',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 1,
                'station_name' => 'Jesus Maria',
                'country' => 'México',
                'state' => 'Aguascalientes',
                'municipality' => 'Barranquillas',
                'address' => 'Paseo de los Chicahuales 196, Corral de Barrancos, CP. 20900',
                'expedition_place' => '20924',
                'server_ip' => '192.168.38.101',
                'database_name' => 'CG_15901',
                'cre_permit' => 'PL/25891/EXP/ES/2024',
                'email' => 'es15901_jesusmaria@totalgas.com',
                'source_system' => 'ControlGas',
                'external_id' => '38',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 5,
                'station_name' => 'Gabriela Mistral',
                'country' => 'México',
                'state' => 'Aguascalientes',
                'municipality' => 'Aguascalientes',
                'address' => 'C. Gabriela Mistral #100, Col. La estrella, CP. 20299',
                'expedition_place' => '20150',
                'server_ip' => '192.168.39.101',
                'database_name' => 'CG_12442',
                'cre_permit' => 'PL/3340/EXP/ES/2015',
                'email' => null,
                'source_system' => 'ControlGas',
                'external_id' => '39',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 8,
                'station_name' => 'PRAXEDIS',
                'country' => 'México',
                'state' => 'Chihuahua',
                'municipality' => 'Praxedis G. Guerrero',
                'address' => 'Av Morelos S/N, CP. 32780',
                'expedition_place' => null,
                'server_ip' => '192.168.40.101',
                'database_name' => 'E10702',
                'cre_permit' => 'PL/10702/EXP/ES/2015',
                'email' => null,
                'source_system' => 'NexusFuel',
                'external_id' => '1',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($stations as $station) {
            Station::updateOrCreate(
                [
                    'source_system' => $station['source_system'],
                    'external_id' => $station['external_id'],
                ],
                $station
            );
        }
    }
}
