<!doctype html><html lang="es"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans;font-size:10px;color:#24364b}table{width:100%;border-collapse:collapse}td,th{border:1px solid #dbe5ed;padding:7px;vertical-align:top}th{background:#eaf6ff;color:#176eaf;text-align:left}.head td,.signatures td{border:0}.label{font-size:8px;text-transform:uppercase;color:#718096}.total{font-size:13px;font-weight:bold;color:#188ae2}.signatures{margin-top:34px}.signature{text-align:center;vertical-align:top}.signature-label{display:block;font-size:8px;font-weight:bold;margin-bottom:28px;text-transform:uppercase}.signature-line{border-top:1px solid #64748b;margin:0 auto 7px;width:84%}.signature-role{color:#718096;display:block;font-size:8px;margin-top:3px}</style></head><body>
<table class="head"><tr><td><img src="{{ $logoPath }}" style="height:38px"><br><strong>{{ $company?->legal_name ?? $company?->name ?? 'TotalGas' }}</strong><br><span class="label">RFC</span> {{ $company?->rfc ?? '—' }}</td><td style="text-align:right"><h2 style="color:#188ae2;margin:0">ORDEN DE COMPRA DIRECTA</h2><strong>{{ $directPurchaseOrder->folio }}</strong><br>Emisión: {{ optional($directPurchaseOrder->issued_at)->format('d/m/Y H:i') }}</td></tr></table>
<br><table><tr><th style="width:50%">Proveedor</th><th>Entrega y control</th></tr><tr><td><strong>{{ $directPurchaseOrder->supplier?->company_name }}</strong><br><span class="label">RFC</span> {{ $directPurchaseOrder->supplier?->rfc ?? '—' }}<br><span class="label">Contacto</span> {{ $directPurchaseOrder->supplier?->contact_person ?? '—' }}</td><td><span class="label">Ubicación de recepción</span><br>{{ $directPurchaseOrder->receivingLocation?->name ?? '—' }}<br><span class="label">Solicitó</span><br>{{ $directPurchaseOrder->creator?->name ?? '—' }}</td></tr></table>
<br><table><thead><tr><th>#</th><th>Descripción</th><th>Centro de costo</th><th style="text-align:right">Cantidad</th><th style="text-align:right">P. unitario</th><th style="text-align:right">Total</th></tr></thead><tbody>@foreach($directPurchaseOrder->items as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->description }}</td><td>{{ $item->costCenter?->code }} {{ $item->costCenter?->name }}</td><td style="text-align:right">{{ number_format((float)$item->quantity, 3) }}</td><td style="text-align:right">${{ number_format((float)$item->unit_price, 2) }}</td><td style="text-align:right">${{ number_format((float)$item->total, 2) }}</td></tr>@endforeach</tbody></table>
<table style="margin-top:12px"><tr><td style="border:0;width:60%"><span class="label">Justificación</span><br>{{ $directPurchaseOrder->justification }}</td><td style="border:0;text-align:right"><div>Subtotal: ${{ number_format((float)$directPurchaseOrder->subtotal,2) }}</div><div>IVA: ${{ number_format((float)$directPurchaseOrder->iva_amount,2) }}</div><div class="total">Total: ${{ number_format((float)$directPurchaseOrder->total,2) }} {{ $directPurchaseOrder->currency }}</div></td></tr></table>
@php
    $signatures = collect([
        ['label' => 'Elaboró', 'name' => $directPurchaseOrder->creator?->name, 'role' => 'Solicitante'],
        ['label' => 'Aceptó', 'name' => $directPurchaseOrder->supplier?->company_name, 'role' => 'Proveedor'],
        ['label' => 'Autorizó', 'name' => $directPurchaseOrder->approver?->name, 'role' => $directPurchaseOrder->authorizerRole?->name ?? 'Autorizador de la OCD'],
        $directPurchaseOrder->receiver ? ['label' => 'Recibió', 'name' => $directPurchaseOrder->receiver->name, 'role' => 'Responsable de recepción'] : null,
    ])->filter(fn ($signature) => filled($signature['name']))->values();
@endphp
@if($signatures->isNotEmpty())<table class="signatures"><tr>@foreach($signatures as $signature)<td class="signature" style="width:{{ 100 / $signatures->count() }}%"><span class="signature-label">{{ $signature['label'] }}</span><div class="signature-line"></div><strong>{{ $signature['name'] }}</strong><span class="signature-role">{{ $signature['role'] }}</span></td>@endforeach</tr></table>@endif
</body></html>
