<?php
namespace App\Services;
use App\Models\CostCenterApprovalStep; use App\Models\DirectPurchaseOrder; use App\Models\QuotationSummary; use App\Models\User; use Illuminate\Database\Eloquent\Model; use Illuminate\Support\Facades\DB;
class CostCenterApprovalFlowService {
 public function initialize(Model $approvable): bool { $items=$approvable instanceof DirectPurchaseOrder?$approvable->items()->with('costCenter.responsible')->get():$approvable->requisition->items()->with('costCenter.responsible')->get(); $amount=(float)$approvable->total; $centers=$items->pluck('costCenter')->filter()->unique('id'); if($centers->isEmpty()) return false; $steps=[]; foreach($centers as $center){ $manager=$center->responsible; if(!$manager) continue; $resolution=$this->resolve($manager,$amount); $steps[$resolution['user']->id] ??= ['center'=>$center,'manager'=>$manager,'resolution'=>$resolution]; } if(!$steps) return false; DB::transaction(function()use($approvable,$steps){ $approvable->approvalSteps()->delete(); foreach(array_values($steps) as $i=>$step){ $approvable->approvalSteps()->create(['step_order'=>$i+1,'cost_center_id'=>$step['center']->id,'responsible_user_id'=>$step['manager']->id,'principal_user_id'=>$step['resolution']['user']->id,'source'=>$step['resolution']['source']]); } $first=$approvable->approvalSteps()->orderBy('step_order')->first(); $this->assign($approvable,$first); }); return true; }
 public function advance(Model $approvable, User $actor, ?string $comments): bool { $step=$approvable->approvalSteps()->where('status','PENDING')->orderBy('step_order')->firstOrFail(); $ctx=app(ApprovalDelegationService::class)->contextFor($actor,$step->principal_user_id); if(!$ctx && !$actor->hasRole('superadmin')) abort(403); $step->update(['status'=>'APPROVED','acted_by_user_id'=>$actor->id,'approval_delegation_id'=>$ctx['delegation']->id??null,'comments'=>$comments,'acted_at'=>now()]); app(ApprovalDecisionService::class)->record($approvable,$step->principal_user_id,$actor,'APPROVED',$comments); $next=$approvable->approvalSteps()->where('status','PENDING')->orderBy('step_order')->first(); if($next){$this->assign($approvable,$next);return false;} return true; }
 private function resolve(User $manager,float $amount):array { $assignment=$manager->authorizerAssignment?->loadMissing('authorizerRole'); $role=$assignment?->authorizerRole; $limit=$manager->activeAuthorizerException?->approval_limit ?? $role?->approval_limit; if($manager->is_active && $role && ($role->approval_limit===null || ($limit!==null && $limit+0.000001>=$amount))) return ['user'=>$manager,'source'=>'COST_CENTER']; $r=app(AuthorizerResolutionService::class)->resolveForRequester($manager,$amount); return ['user'=>$r['approver_user'],'source'=>'HIERARCHY']; }
 private function assign(Model $a,CostCenterApprovalStep $s):void { $a instanceof QuotationSummary?$a->update(['current_approver_user_id'=>$s->principal_user_id]):$a->update(['assigned_approver_id'=>$s->principal_user_id]); }
}
