SET NOCOUNT ON;

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'vtt_cat_prov'
ORDER BY ORDINAL_POSITION;

SELECT COUNT(*) AS total_rows
FROM dbo.vtt_cat_prov;

SELECT TOP (10) *
FROM dbo.vtt_cat_prov;
