@extends('layouts.zircos')

@section('title', 'Reportería')
@section('page.title', 'Reportería')

@push('styles')
<style>
.reports-hero,.report-card,.reports-month-chart{border:1px solid #e2e9f0;border-radius:.85rem;background:#fff;box-shadow:0 6px 20px rgba(28,80,120,.05)}.reports-hero{padding:1.25rem 1.4rem;margin-bottom:1rem;background:#f7fbff}.reports-kicker{color:#188ae2;font-weight:800;font-size:.72rem;letter-spacing:.07em;text-transform:uppercase}.reports-month-chart{padding:1.1rem 1.25rem;margin:1rem 0}.reports-chart-head{display:flex;justify-content:space-between;align-items:start;gap:1rem;margin-bottom:1rem}.reports-chart-title{font-size:1rem;font-weight:700;color:#24364b}.reports-chart-subtitle{font-size:.78rem;color:#718096}.reports-chart-total{font-weight:800;color:#188ae2;text-align:right}.reports-chart-row{display:grid;grid-template-columns:minmax(130px,190px) 1fr 42px;align-items:center;gap:.75rem;margin:.72rem 0;font-size:.8rem}.reports-chart-track{height:.65rem;border-radius:999px;background:#eef3f7;overflow:hidden}.reports-chart-bar{height:100%;border-radius:inherit;min-width:.35rem;transition:width .35s ease}.reports-chart-value{text-align:right;font-weight:700;color:#24364b}.reports-chart-empty{color:#718096;font-size:.85rem;padding:.7rem 0}.report-card{height:100%;padding:1rem;transition:transform .18s,box-shadow .18s}.report-card:hover{transform:translateY(-3px);box-shadow:0 12px 26px rgba(24,138,226,.13)}.report-icon{width:2.5rem;height:2.5rem;border-radius:.7rem;display:grid;place-items:center;background:#eaf6ff;color:#188ae2;font-size:1.25rem}.report-card p{font-size:.8rem;color:#718096;margin:.45rem 0 .8rem}@media(max-width:575px){.reports-chart-row{grid-template-columns:110px 1fr 32px}}@media (prefers-reduced-motion:reduce){.report-card,.reports-chart-bar{transition:none}.report-card:hover{transform:none}}
</style>
@endpush

@section('content')
<div class="reports-hero d-flex flex-wrap align-items-center gap-3"><div class="report-icon"><i class="ti ti-chart-bar"></i></div><div><span class="reports-kicker">Control ejecutivo</span><h5 class="mb-1">Reportería integral</h5><p class="mb-0 text-muted small">Consulta el ciclo completo de requisiciones, compras, proveedores, presupuesto y contratos.</p></div></div>
<section class="reports-month-chart" aria-labelledby="monthlyStatusTitle"><div class="reports-chart-head"><div><span class="reports-kicker">Seguimiento operativo</span><h2 id="monthlyStatusTitle" class="reports-chart-title mb-1">Requisiciones por estatus</h2><p class="reports-chart-subtitle mb-0">Creadas durante {{ $monthlyStatus['period'] }}.</p></div><div class="reports-chart-total"><span class="d-block small text-muted fw-normal">Total del mes</span>{{ $monthlyStatus['total'] }}</div></div>@if($monthlyStatus['total'])@foreach($monthlyStatus['rows'] as $item)<div class="reports-chart-row"><span>{{ $item['label'] }}</span><div class="reports-chart-track" role="progressbar" aria-label="{{ $item['label'] }}" aria-valuenow="{{ $item['total'] }}" aria-valuemin="0" aria-valuemax="{{ $monthlyStatus['total'] }}"><div class="reports-chart-bar" style="width: {{ ($item['total'] / $monthlyStatus['total']) * 100 }}%;background:{{ $item['color'] }}"></div></div><span class="reports-chart-value">{{ $item['total'] }}</span></div>@endforeach @else<div class="reports-chart-empty"><i class="ti ti-chart-bar-off me-1"></i>No hay requisiciones creadas en el mes en curso.</div>@endif</section>
@foreach(collect($reports)->groupBy(fn($report) => $report[1], preserveKeys: true) as $group => $items)
<h6 class="text-uppercase text-muted fs-12 mt-4 mb-2">{{ $group }}</h6><div class="row g-3">
@foreach($items as $key => $report)<div class="col-md-6 col-xl-4"><a class="report-card d-block text-reset text-decoration-none" href="{{ route('reports.show',$key) }}"><div class="d-flex gap-3"><div class="report-icon"><i class="ti {{ $report[2] }}"></i></div><div><h6 class="mb-0">{{ $report[0] }}</h6><p>Filtros, indicadores, detalle y exportación.</p><span class="text-primary small fw-semibold">Abrir reporte <i class="ti ti-arrow-right"></i></span></div></div></a></div>@endforeach
</div>@endforeach
@endsection
