@extends('layouts.zircos')
@section('title', $title)
@section('page.title', $title)
@push('styles')
<style>
.report-shell,.report-filter,.report-kpi{border:1px solid #e2e9f0;border-radius:.85rem;background:#fff;box-shadow:0 6px 20px rgba(28,80,120,.05)}.report-shell{overflow:visible}.report-head{padding:1.1rem 1.25rem;border-bottom:1px solid #e2e9f0;background:#f7fbff}.report-filter{padding:.9rem;margin:1rem}.report-kpi{padding:.8rem .95rem}.report-kpi span{display:block;color:#718096;font-size:.69rem;text-transform:uppercase;font-weight:700}.report-kpi strong{font-size:1.2rem;color:#24364b}.select2-container{width:100%!important}.select2-container--bootstrap-5 .select2-selection{min-height:38px}@media(max-width:767px){.report-filter .btn{width:100%}}@media(prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important}}
</style>
@endpush
@section('content')
<div class="report-shell"><div class="report-head d-flex flex-wrap justify-content-between align-items-center gap-2"><div><span class="text-primary small fw-bold text-uppercase">Reportería</span><h5 class="mb-0">{{ $title }}</h5></div><a class="btn btn-sm btn-light" href="{{ route('reports.index') }}"><i class="ti ti-arrow-left"></i> Catálogo</a></div>
<form id="reportFilters" class="report-filter"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small">Desde</label><input class="form-control" type="date" name="date_from" value="{{ $defaultFrom }}"></div><div class="col-md-3"><label class="form-label small">Hasta</label><input class="form-control" type="date" name="date_to" value="{{ $defaultTo }}"></div><div class="col-md-3"><label class="form-label small">Empresa</label><select class="form-select js-select" name="company_id"><option value="">Todas</option>@foreach($filters['companies'] as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">Centro de costo</label><select class="form-select js-select" name="cost_center_id"><option value="">Todos</option>@foreach($filters['costCenters'] as $item)<option value="{{ $item->id }}">{{ $item->code }} - {{ $item->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">Departamento</label><select class="form-select js-select" name="department_id"><option value="">Todos</option>@foreach($filters['departments'] as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">Requisitor</label><select class="form-select js-select" name="requisitioner_id"><option value="">Todos</option>@foreach($filters['users'] as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label small">Proveedor</label><select class="form-select js-select" name="supplier_id"><option value="">Todos</option>@foreach($filters['suppliers'] as $item)<option value="{{ $item->id }}">{{ $item->business_name }}</option>@endforeach</select></div><div class="col-md-3"><button class="btn btn-primary w-100" type="submit"><i class="ti ti-filter"></i> Aplicar filtros</button></div></div></form>
<div class="px-3 pb-3"><div id="reportKpis" class="row g-2 mb-3"></div><div class="table-responsive"><table id="reportTable" class="table table-hover nowrap w-100"><thead></thead></table></div></div></div>
@endsection
@push('scripts')
<script>
$(function(){const $form=$('#reportFilters'), url=@json(route('reports.data',$report)); $('.js-select').select2({theme:'bootstrap-5',width:'100%',dropdownParent:$(document.body)});let table;
function exports(){const q=$form.serialize();return [{text:'<i class="ti ti-file-spreadsheet"></i> Excel',className:'btn btn-success btn-sm',action:()=>window.location=@json(route('reports.export',[$report,'xlsx']))+'?'+q},{text:'CSV',className:'btn btn-outline-secondary btn-sm',action:()=>window.location=@json(route('reports.export',[$report,'csv']))+'?'+q},{text:'PDF',className:'btn btn-outline-danger btn-sm',action:()=>window.location=@json(route('reports.export',[$report,'pdf']))+'?'+q}];}
function metrics(json){const cols=json.columns||[];$('#reportTable thead').html('<tr>'+cols.map(c=>'<th>'+c+'</th>').join('')+'</tr>');$('#reportKpis').html(Object.entries(json.kpis||{}).map(([k,v])=>'<div class="col-6 col-lg-3"><div class="report-kpi"><span>'+k+'</span><strong>'+((typeof v==='number')?new Intl.NumberFormat('es-MX',{maximumFractionDigits:2}).format(v):v)+'</strong></div></div>').join(''));}
function load(){if(table){table.destroy();$('#reportTable').empty().append('<thead></thead>');}$.getJSON(url,$form.serialize()).done(function(initial){metrics(initial);const keys=Object.keys(initial.data?.[0]||{});table=$('#reportTable').DataTable({processing:true,serverSide:true,searching:true,responsive:true,ajax:{url,data:()=>Object.fromEntries(new URLSearchParams($form.serialize())),dataSrc:function(json){metrics(json);return json.data;}},columns:keys.map(key=>({data:key})),dom:"<'d-flex flex-wrap justify-content-between gap-2 mb-2'Bf>rt<'d-flex justify-content-between mt-2'ip>",buttons:exports(),language:{url:@json(asset('assets/vendor/datatables.net/es-MX.json')}}});}).fail(function(){$('#reportKpis').html('<div class="col-12"><div class="alert alert-danger mb-0">No fue posible cargar el reporte. Intenta nuevamente.</div></div>');});}
$form.on('submit',function(e){e.preventDefault();load();});load();});
</script>
@endpush
