<?php

/*
|--------------------------------------------------------------------------
| Reportes solicitados por Contabilidad y Finanzas (sección temporal)
|--------------------------------------------------------------------------
| Catálogo de los 31 reportes de docs/reportes/prompts_reportes_portal_proveedores.md.
| "feasibility" es el orden de factibilidad (1 = más factible) según el estado actual
| del portal; "existing_report" apunta al reporte de Reportería que ya cubre una parte.
*/

return [

    'domains' => [
        'A' => ['name' => 'Presupuesto y control del compromiso', 'icon' => 'ti-chart-pie'],
        'B' => ['name' => 'Requisiciones, autorizaciones y órdenes de compra', 'icon' => 'ti-shopping-cart'],
        'C' => ['name' => 'Recepción y devengo', 'icon' => 'ti-package'],
        'D' => ['name' => 'Validación fiscal, IVA y complementos de pago', 'icon' => 'ti-file-invoice'],
        'E' => ['name' => 'Cuentas por pagar y tesorería', 'icon' => 'ti-cash'],
        'F' => ['name' => 'Contabilidad e integración', 'icon' => 'ti-book'],
        'G' => ['name' => 'Cumplimiento del proveedor y REPSE', 'icon' => 'ti-shield-check'],
        'H' => ['name' => 'Auditoría interna e indicadores', 'icon' => 'ti-eye-check'],
    ],

    'reports' => [
        [
            'code' => 'RP-01', 'domain' => 'A', 'phase' => 'F1', 'feasibility' => 2, 'existing_report' => 'budget-execution',
            'name' => 'Presupuesto vs. ejercido por departamento y renglón',
            'purpose' => 'El saldo realmente disponible antes de comprometer un peso más. Contesta "¿puedo autorizar esta compra?" con un número y usa la misma lógica que el bloqueo de la requisición.',
            'frequency' => 'Tiempo real, con corte diario histórico',
            'consumers' => 'Contraloría, jefes de departamento, Dirección de Finanzas',
            'granularity' => 'Empresa + centro de costo + renglón presupuestal + periodo (mes y acumulado).',
            'fields' => ['Empresa, centro de costo, renglón y cuenta contable', 'Autorizado, ampliaciones, reducciones y vigente', 'Reservado, comprometido, devengado y pagado', 'Ejercido, disponible, % de avance, semáforo y proyección de cierre'],
        ],
        [
            'code' => 'RP-02', 'domain' => 'A', 'phase' => 'F1', 'feasibility' => 1, 'existing_report' => 'budget-movements-risk',
            'name' => 'Movimientos y traspasos presupuestales',
            'purpose' => 'La historia de por qué el presupuesto de hoy no es el que se aprobó en enero: cada ampliación, reducción o traspaso con su motivo y autorizador.',
            'frequency' => 'Bajo demanda',
            'consumers' => 'Contraloría, Dirección de Finanzas',
            'granularity' => 'Un movimiento de presupuesto (ampliación, reducción o traspaso).',
            'fields' => ['Folio, fecha, tipo e importe', 'Centro de costo y renglón origen y destino', 'Motivo, solicitante y autorizador', 'Nivel de autorización aplicado y documento soporte'],
        ],
        [
            'code' => 'RP-03', 'domain' => 'A', 'phase' => 'F1', 'feasibility' => 16, 'existing_report' => null,
            'name' => 'Alertas de agotamiento, sobregiro y excepciones autorizadas',
            'purpose' => 'Aviso antes del sobregiro, no en el cierre, y el listado auditable de cada compra autorizada sin presupuesto con el nombre de quien la autorizó.',
            'frequency' => 'Batch diario + disparo por evento',
            'consumers' => 'Contraloría, jefes de departamento',
            'granularity' => 'Un renglón presupuestal en riesgo o con excepción aplicada.',
            'fields' => ['% consumido, disponible y ritmo de gasto de 3 meses', 'Mes proyectado de agotamiento', 'Documentos en trámite que provocarían el sobregiro', 'Excepciones: folio, importe, autorizador, motivo y fecha'],
        ],
        [
            'code' => 'RC-01', 'domain' => 'B', 'phase' => 'F1', 'feasibility' => 3, 'existing_report' => 'requisition-traceability',
            'name' => 'Pipeline de requisiciones y tiempos de ciclo',
            'purpose' => 'Dónde se atoran las compras y con quién: el paso, el aprobador pendiente y las horas transcurridas en cada requisición.',
            'frequency' => 'Diaria',
            'consumers' => 'Compras, Contraloría, jefes de departamento',
            'granularity' => 'Una requisición, con detalle por paso de autorización.',
            'fields' => ['Folio, fecha, solicitante, centro de costo, importe y marca REPSE', 'Estatus, paso detenido y aprobador pendiente', 'Horas en el paso actual y tiempo total de ciclo', 'Motivo de rechazo o cancelación'],
        ],
        [
            'code' => 'RC-02', 'domain' => 'B', 'phase' => 'F1', 'feasibility' => 6, 'existing_report' => 'purchase-orders-control',
            'name' => 'Órdenes de compra emitidas',
            'purpose' => 'El universo del compromiso del periodo y la proporción de OC directas, para detectar si el control por requisición se está saltando.',
            'frequency' => 'Diaria y bajo demanda',
            'consumers' => 'Compras, Contraloría',
            'granularity' => 'Una orden de compra, con detalle por renglón.',
            'fields' => ['Folio, empresa, proveedor y RFC', 'Origen (requisición, directa, contrato) y tipo (cerrada, abierta)', 'Moneda, subtotal, impuestos, retenciones y total', 'Comprador, estatus, fecha de envío y acuse del proveedor'],
        ],
        [
            'code' => 'RC-03', 'domain' => 'B', 'phase' => 'F1', 'feasibility' => 4, 'existing_report' => 'critical-orders',
            'name' => 'Órdenes de compra abiertas y backlog por recibir',
            'purpose' => 'El compromiso vivo que todavía no llega: flujo de efectivo futuro y presupuesto apartado. Expone las OC "zombis" que conviene cerrar.',
            'frequency' => 'Semanal',
            'consumers' => 'Compras, Contraloría, Tesorería',
            'granularity' => 'Un renglón de OC con saldo pendiente de recibir.',
            'fields' => ['Folio, fecha, proveedor y renglón', 'Cantidad ordenada, recibida y pendiente; importe pendiente', 'Fecha prometida, días de atraso y vigencia', 'OC abiertas: monto máximo, consumido, saldo y % de agotamiento'],
        ],
        [
            'code' => 'RC-04', 'domain' => 'B', 'phase' => 'F1', 'feasibility' => 18, 'existing_report' => null,
            'name' => 'Modificaciones, adendas y cancelaciones de OC',
            'purpose' => 'Detecta la práctica de aprobar barato y subir después: todo aumento posterior a la autorización queda con nombre, monto y fecha.',
            'frequency' => 'Bajo demanda',
            'consumers' => 'Contraloría, auditoría interna',
            'granularity' => 'Una versión modificada de una orden de compra.',
            'fields' => ['Folio, versión y campo modificado', 'Valor anterior, valor nuevo y delta en importe y %', 'Motivo y usuario que modificó', 'Si requirió re-aprobación, quién re-aprobó y fecha'],
        ],
        [
            'code' => 'RC-05', 'domain' => 'B', 'phase' => 'F2', 'feasibility' => 10, 'existing_report' => null,
            'name' => 'Concentración de gasto y detección de fraccionamiento',
            'purpose' => 'Dos riesgos en un reporte: dependencia excesiva de un proveedor y compras partidas para no subir de nivel de autorización.',
            'frequency' => 'Mensual',
            'consumers' => 'Contraloría, Dirección',
            'granularity' => 'Un proveedor, con vistas por comprador y por familia de producto o servicio.',
            'fields' => ['Proveedor, RFC, monto y % del gasto', 'Número de OC, ticket promedio y antigüedad de la relación', 'Operaciones justo por debajo de un umbral de autorización', 'Compras al mismo proveedor y familia en una ventana de N días'],
        ],
        [
            'code' => 'RR-01', 'domain' => 'C', 'phase' => 'F1', 'feasibility' => 8, 'existing_report' => 'receptions-differences',
            'name' => 'Recepciones validadas y su evidencia',
            'purpose' => 'La prueba material del gasto en un solo lugar: quién recibió, quién validó y los archivos de evidencia de cada recepción.',
            'frequency' => 'Diaria',
            'consumers' => 'Contraloría, auditoría, Cuentas por pagar',
            'granularity' => 'Un evento de recepción, con sus archivos de evidencia.',
            'fields' => ['Folio de recepción, OC, proveedor, tipo y fecha', 'Cantidad recibida por renglón', 'Quién recibió, quién validó y ubicación', 'Adjuntos: nombre, tipo, hash, fecha de carga y usuario'],
        ],
        [
            'code' => 'RR-02', 'domain' => 'C', 'phase' => 'F1', 'feasibility' => 7, 'existing_report' => null,
            'name' => 'Recepciones pendientes de facturar (provisión de cierre)',
            'purpose' => 'El cálculo automático de la provisión de gasto devengado no facturado, soportado renglón por renglón para el cierre y la auditoría.',
            'frequency' => 'Cierre mensual y bajo demanda',
            'consumers' => 'Contabilidad, Contraloría',
            'granularity' => 'Un renglón recibido y validado sin CFDI vinculado a la fecha de corte.',
            'fields' => ['OC, renglón, proveedor y fecha de recepción', 'Días transcurridos, cantidad y precio de OC', 'Importe a provisionar sin IVA, moneda y tipo de cambio', 'Cuenta contable, centro de costo y renglón presupuestal'],
        ],
        [
            'code' => 'RR-03', 'domain' => 'C', 'phase' => 'F1', 'feasibility' => 13, 'existing_report' => null,
            'name' => 'Excepciones de flujo',
            'purpose' => 'El termómetro de qué tan real es el proceso: documentos que rompieron la secuencia esperada (hechos consumados en lugar de control previo).',
            'frequency' => 'Semanal',
            'consumers' => 'Contraloría',
            'granularity' => 'Un documento que rompió la secuencia esperada del proceso.',
            'fields' => ['Factura sin recepción, recepción sin OC, OC directa no autorizada', 'Factura anterior a la OC, recepción posterior a la vigencia', 'Documento, proveedor, importe, usuario y fecha', 'Estatus de regularización y responsable'],
        ],
        [
            'code' => 'RF-01', 'domain' => 'D', 'phase' => 'F1', 'feasibility' => 12, 'existing_report' => null,
            'name' => 'Bitácora de validación de CFDI',
            'purpose' => 'Por qué se rechazan las facturas y a quién más, para corregir al proveedor con datos y medir si el motor de validación está bien calibrado.',
            'frequency' => 'Tiempo real',
            'consumers' => 'Fiscal, Cuentas por pagar, proveedor',
            'granularity' => 'Un intento de carga de un CFDI.',
            'fields' => ['Fecha, UUID, RFC emisor, empresa receptora y total', 'Tipo de comprobante y resultado (aceptado/rechazado)', 'Código de rechazo y regla incumplida', 'Mensaje al proveedor, número de intento y canal'],
        ],
        [
            'code' => 'RF-02', 'domain' => 'D', 'phase' => 'F1', 'feasibility' => 11, 'existing_report' => null,
            'name' => 'Resultado del cotejo triple y desviaciones',
            'purpose' => 'El sobreprecio y la sobrefacturación cuantificados en pesos (OC vs. recepción vs. factura) y quién libera las desviaciones.',
            'frequency' => 'Diaria',
            'consumers' => 'Compras, Contraloría, Cuentas por pagar',
            'granularity' => 'Una factura cotejada, con detalle por renglón.',
            'fields' => ['UUID, OC, recepción y renglón', 'Precio OC vs. facturado; cantidad recibida vs. facturada', 'Importe y % de desviación contra la tolerancia', 'Resultado y usuario que autorizó el desvío'],
        ],
        [
            'code' => 'RF-03', 'domain' => 'D', 'phase' => 'F2', 'feasibility' => 27, 'existing_report' => null,
            'name' => 'IVA acreditable y conciliación para la DIOT',
            'purpose' => 'La DIOT armada desde el origen y la conciliación del IVA acreditable del portal contra la balanza contable.',
            'frequency' => 'Mensual',
            'consumers' => 'Fiscal',
            'granularity' => 'Un proveedor (RFC) y tipo de operación, con detalle por CFDI.',
            'fields' => ['RFC, razón social, tipo de tercero y de operación', 'Base gravada por tasa: 16 %, 8 %, 0 %, exento, no objeto', 'IVA trasladado, pagado en el mes y retenido', 'IVA acreditable y pendiente de acreditar (PPD sin REP)'],
        ],
        [
            'code' => 'RF-04', 'domain' => 'D', 'phase' => 'F2', 'feasibility' => 22, 'existing_report' => null,
            'name' => 'Retenciones efectuadas y su entero',
            'purpose' => 'Control de que se retuvo lo que correspondía y se enteró lo que se retuvo; evita gastos no deducibles y créditos fiscales.',
            'frequency' => 'Mensual',
            'consumers' => 'Fiscal, Contabilidad',
            'granularity' => 'Un CFDI con retención, agregado por tipo y proveedor.',
            'fields' => ['UUID, proveedor, tipo de persona, concepto y base', 'Retención de ISR y de IVA; importe retenido', 'Mes de causación, mes de entero y declaración', 'CFDI de retenciones emitido, cuando aplique'],
        ],
        [
            'code' => 'RF-05', 'domain' => 'D', 'phase' => 'F2', 'feasibility' => 25, 'existing_report' => null,
            'name' => 'Control de complementos de pago (REP)',
            'purpose' => 'El IVA que todavía no se puede acreditar y la lista exacta de proveedores a quienes reclamar su complemento de pago.',
            'frequency' => 'Semanal, con corte al inicio de cada mes',
            'consumers' => 'Fiscal, Cuentas por pagar',
            'granularity' => 'Un pago aplicado a una factura PPD.',
            'fields' => ['UUID de la factura, fecha y monto del pago', 'Parcialidad y saldo insoluto', 'UUID y fecha del REP, días transcurridos y estatus de plazo', 'Diferencia pagado vs. REP y efecto en el semáforo'],
        ],
        [
            'code' => 'RF-06', 'domain' => 'D', 'phase' => 'F2', 'feasibility' => 24, 'existing_report' => null,
            'name' => 'CFDI de egreso, anticipos y ajustes',
            'purpose' => 'Control del dinero entregado por adelantado y de los saldos a favor: notas de crédito y anticipos pendientes de aplicar.',
            'frequency' => 'Mensual',
            'consumers' => 'Cuentas por pagar, Contabilidad',
            'granularity' => 'Una nota de crédito o un anticipo entregado.',
            'fields' => ['UUID del egreso, UUID relacionados y tipo de relación', 'Motivo: devolución, descuento, bonificación o anticipo', 'Importe, IVA y saldo del anticipo antes y después', 'Efecto en la cuenta por pagar, la póliza y el presupuesto'],
        ],
        [
            'code' => 'RF-07', 'domain' => 'D', 'phase' => 'F3', 'feasibility' => 31, 'existing_report' => null,
            'name' => 'Conciliación del portal contra el repositorio del SAT',
            'purpose' => 'Certeza de que lo deducido existe y sigue vigente; detecta facturas canceladas por el proveedor después de provisionarlas o pagarlas.',
            'frequency' => 'Mensual',
            'consumers' => 'Fiscal, Contraloría',
            'granularity' => 'Un UUID con diferencia entre el SAT y el portal.',
            'fields' => ['UUID, RFC emisor, fecha y total', 'Estatus en el SAT y en el portal', 'Tipo de diferencia (faltante, cancelado tras provisionar o pagar, duplicado)', 'Importe expuesto, acción sugerida y responsable'],
        ],
        [
            'code' => 'RT-01', 'domain' => 'E', 'phase' => 'F1', 'feasibility' => 23, 'existing_report' => null,
            'name' => 'Programación semanal de pagos por vencimiento',
            'purpose' => 'La propuesta de pago lista para autorizar y generar el layout bancario, garantizando que nada bloqueado se cuele.',
            'frequency' => 'Semanal, con día y hora de corte fijos',
            'consumers' => 'Tesorería, Dirección de Finanzas',
            'granularity' => 'Un documento propuesto a pago, por semana, empresa y banco.',
            'fields' => ['Proveedor, banco y CLABE validada', 'UUID, folio de OC, importe y moneda', 'Vencimiento, días de atraso, prioridad y pronto pago', 'Bloqueos activos y totales por empresa, banco y semana'],
        ],
        [
            'code' => 'RT-02', 'domain' => 'E', 'phase' => 'F1', 'feasibility' => 21, 'existing_report' => null,
            'name' => 'Antigüedad de saldos por proveedor',
            'purpose' => 'La foto del pasivo real con proveedores y del riesgo de suspensión de suministro; alimenta la revelación en estados financieros.',
            'frequency' => 'Semanal y al cierre mensual',
            'consumers' => 'Tesorería, Contabilidad, Contraloría',
            'granularity' => 'Un proveedor con cubos de antigüedad y detalle por documento.',
            'fields' => ['Proveedor, RFC y saldo total', 'Por vencer, 1-30, 31-60, 61-90 y más de 90 días', 'Moneda extranjera y su equivalente en pesos', 'Documentos en disputa o bloqueados y días de crédito'],
        ],
        [
            'code' => 'RT-03', 'domain' => 'E', 'phase' => 'F1', 'feasibility' => 20, 'existing_report' => null,
            'name' => 'Estado de cuenta de proveedor',
            'purpose' => 'Que el proveedor se conteste solo "¿cuándo me pagan?" desde el portal, viendo exactamente el mismo documento que Cuentas por pagar.',
            'frequency' => 'Bajo demanda y envío automático mensual',
            'consumers' => 'Proveedor, Cuentas por pagar',
            'granularity' => 'Un movimiento (factura, nota de crédito, anticipo o pago) de un proveedor y empresa.',
            'fields' => ['Fecha, tipo de documento, UUID o folio y OC', 'Cargo, abono y saldo acumulado', 'Fecha de vencimiento y estatus', 'Motivo de bloqueo o disputa y fecha estimada de pago'],
        ],
        [
            'code' => 'RT-04', 'domain' => 'E', 'phase' => 'F3', 'feasibility' => 29, 'existing_report' => null,
            'name' => 'Proyección de salidas de efectivo a 13 semanas',
            'purpose' => 'Visibilidad del flujo más allá de la semana en curso, construida con el compromiso ya contraído en el portal.',
            'frequency' => 'Semanal',
            'consumers' => 'Dirección de Finanzas, Tesorería',
            'granularity' => 'Una semana y concepto, con apertura por empresa.',
            'fields' => ['Cuentas por pagar vencidas y por vencer', 'Compromiso de OC no facturado con fecha esperada', 'Contratos recurrentes y pagos fijos', 'Total proyectado, disponible estimado y brecha'],
        ],
        [
            'code' => 'RK-01', 'domain' => 'F', 'phase' => 'F2', 'feasibility' => 26, 'existing_report' => null,
            'name' => 'Auxiliar de pólizas generadas y archivo de exportación',
            'purpose' => 'Trazabilidad entre cada asiento contable y el documento que lo originó; elimina la recaptura en contabilidad.',
            'frequency' => 'Diaria y al cierre',
            'consumers' => 'Contabilidad',
            'granularity' => 'Un movimiento contable (cargo o abono) generado por el portal.',
            'fields' => ['Folio, tipo, fecha y concepto de la póliza', 'Cuenta contable, centro de costo, cargo y abono', 'Referencia a UUID, OC, recepción y pago', 'Estatus de exportación y folio del sistema contable'],
        ],
        [
            'code' => 'RK-02', 'domain' => 'F', 'phase' => 'F2', 'feasibility' => 30, 'existing_report' => null,
            'name' => 'Conciliación del portal contra la contabilidad',
            'purpose' => 'El cierre del círculo: exhibe los asientos de proveedores hechos fuera del portal hasta que la diferencia llegue a cero.',
            'frequency' => 'Mensual',
            'consumers' => 'Contabilidad, Contraloría',
            'granularity' => 'Una diferencia entre el saldo del portal y el saldo contable de una cuenta.',
            'fields' => ['Cuenta, empresa, saldo en portal y en contabilidad', 'Diferencia y su clasificación', 'Provisión no exportada, póliza manual, cancelación o diferencia cambiaria', 'Documento y responsable asociados'],
        ],
        [
            'code' => 'RM-01', 'domain' => 'G', 'phase' => 'F2', 'feasibility' => 17, 'existing_report' => null,
            'name' => 'Matriz de cumplimiento y semáforo de proveedores',
            'purpose' => 'El riesgo de toda la base de proveedores en una vista, con el monto expuesto al lado, para decidir un bloqueo con información.',
            'frequency' => 'Tiempo real con recálculo diario',
            'consumers' => 'Contraloría, Compras, Fiscal',
            'granularity' => 'Un proveedor por empresa con la que opera.',
            'fields' => ['RFC, razón social, semáforo y régimen fiscal', 'CSF, opinión 32-D y situación 69-B', 'Registro REPSE, contrato y expediente mensual', 'Motivo del color, operaciones vivas y saldo expuesto'],
        ],
        [
            'code' => 'RM-02', 'domain' => 'G', 'phase' => 'F2', 'feasibility' => 5, 'existing_report' => null,
            'name' => 'Vencimientos documentales del expediente',
            'purpose' => 'La cobranza documental convertida en agenda, con recordatorios al proveedor antes de que ocurra el bloqueo.',
            'frequency' => 'Semanal',
            'consumers' => 'Compras, Contraloría',
            'granularity' => 'Un documento del expediente con fecha de vigencia.',
            'fields' => ['Proveedor y tipo de documento', 'Fecha de emisión, vencimiento y días restantes', 'Estatus, responsable interno y recordatorios enviados', 'Efecto al vencer: amarillo, rojo o bloqueo'],
        ],
        [
            'code' => 'RM-03', 'domain' => 'G', 'phase' => 'F3', 'feasibility' => 19, 'existing_report' => null,
            'name' => 'Auditoría mensual de proveedores REPSE',
            'purpose' => 'El expediente mensual que sostiene la deducción y el acreditamiento en servicios especializados, y base de las informativas IMSS/INFONAVIT.',
            'frequency' => 'Mensual',
            'consumers' => 'Contraloría, Fiscal, Recursos Humanos',
            'granularity' => 'Un contrato REPSE por mes, con detalle por trabajador.',
            'fields' => ['Proveedor, folio REPSE, vigencia y contrato', 'Estaciones, trabajadores declarados y CFDI de nómina', 'Pagos de ISR, IMSS, INFONAVIT e IVA del mes', 'Estatus por requisito y cobertura de nómina'],
        ],
        [
            'code' => 'RM-04', 'domain' => 'G', 'phase' => 'F3', 'feasibility' => 9, 'existing_report' => null,
            'name' => 'Monitoreo del listado 69-B y proveedores bloqueados',
            'purpose' => 'Cuantifica la exposición cuando un proveedor aparece en el listado del SAT, incluyendo operaciones de ejercicios anteriores.',
            'frequency' => 'Diaria',
            'consumers' => 'Contraloría, Fiscal, Dirección',
            'granularity' => 'Una coincidencia entre un RFC del padrón y una publicación del SAT.',
            'fields' => ['RFC, razón social y situación en el 69-B', 'Fecha de publicación y número de oficio', 'Operaciones históricas: número, importe y ejercicios', 'IVA e ISR expuestos, acción tomada y plazo'],
        ],
        [
            'code' => 'RA-01', 'domain' => 'H', 'phase' => 'F2', 'feasibility' => 15, 'existing_report' => null,
            'name' => 'Bitácora de excepciones, liberaciones y overrides',
            'purpose' => 'El registro de todas las veces que el proceso cedió, con monto y responsable. Es lo primero que pide un auditor.',
            'frequency' => 'Continua',
            'consumers' => 'Contraloría, auditoría interna',
            'granularity' => 'Una acción que anuló, saltó o relajó un control.',
            'fields' => ['Fecha, usuario, rol e IP', 'Tipo: sobregiro, liberación fiscal, tolerancia, pago urgente o alta incompleta', 'Documento afectado e importe', 'Motivo, autorizador y evidencia'],
        ],
        [
            'code' => 'RA-02', 'domain' => 'H', 'phase' => 'F3', 'feasibility' => 14, 'existing_report' => null,
            'name' => 'Segregación de funciones e integridad de accesos',
            'purpose' => 'Verifica que la matriz de roles no se degrade con el uso (perfiles prestados, permisos incompatibles, cuentas inactivas).',
            'frequency' => 'Mensual',
            'consumers' => 'Contraloría, Sistemas, auditoría',
            'granularity' => 'Un usuario con permisos incompatibles o un evento de conflicto.',
            'fields' => ['Usuario, roles y combinaciones incompatibles', 'Documentos donde se materializó el conflicto', 'Altas, bajas y cambios de rol del periodo', 'Último acceso y cuentas inactivas'],
        ],
        [
            'code' => 'RA-03', 'domain' => 'H', 'phase' => 'F3', 'feasibility' => 28, 'existing_report' => null,
            'name' => 'Tablero de indicadores de Contraloría',
            'purpose' => 'La medición del control, no de la operación: metas concretas por indicador y su avance con datos del propio sistema.',
            'frequency' => 'Mensual',
            'consumers' => 'Dirección, Contraloría',
            'granularity' => 'Un indicador por periodo, con apertura por empresa y departamento.',
            'fields' => ['% de gasto sin OC previa y % de OC directas', 'Tiempos de ciclo y días de pago promedio', '% de facturas rechazadas y proveedores en verde', 'Excepciones autorizadas, IVA pendiente y desviación presupuestal'],
        ],
    ],

];
