<?php

return [
    'modules' => [
        'dashboard' => ['permission' => 'dashboard.ver', 'label' => 'Dashboard', 'description' => 'Acceso al tablero principal.', 'category' => 'Inicio'],
        'reports' => ['permission' => 'reportes.ver', 'label' => 'Reportería', 'description' => 'Consulta de reportes del portal.', 'category' => 'Información'],
        'requisitions' => ['permission' => 'requisiciones.ver', 'label' => 'Requisiciones', 'description' => 'Consulta y operación de requisiciones.', 'category' => 'Compras'],
        'requisitions_main' => ['permission' => 'requisiciones.principal.ver', 'parent' => 'requisitions', 'label' => 'Mis requisiciones', 'description' => 'Vista principal de requisiciones.', 'category' => 'Compras'],
        'requisitions_contract' => ['permission' => 'requisiciones.contrato.ver', 'parent' => 'requisitions', 'label' => 'Requisiciones por contrato', 'description' => 'Vista de requisiciones por contrato.', 'category' => 'Compras'],
        'quotations' => ['permission' => 'cotizaciones.ver', 'label' => 'Cotizaciones', 'description' => 'Acceso al flujo de cotizaciones y RFQ.', 'category' => 'Compras'],
        'quotations_list' => ['permission' => 'cotizaciones.lista.ver', 'parent' => 'quotations', 'label' => 'Listado de cotizaciones', 'description' => 'Vista principal de cotizaciones.', 'category' => 'Compras'],
        'quotations_approvals' => ['permission' => 'cotizaciones.aprobaciones.ver', 'parent' => 'quotations', 'label' => 'Aprobaciones de cotizaciones', 'description' => 'Bandeja de aprobación de cotizaciones.', 'category' => 'Compras'],
        'quotations_planner' => ['permission' => 'cotizaciones.planeador.ver', 'parent' => 'quotations', 'label' => 'Planeador de cotizaciones', 'description' => 'Planeación de solicitudes de cotización.', 'category' => 'Compras'],
        'quotations_rfq' => ['permission' => 'cotizaciones.rfq.ver', 'parent' => 'quotations', 'label' => 'Solicitudes de cotización', 'description' => 'Vista de solicitudes de cotización.', 'category' => 'Compras'],
        'quotations_inbox' => ['permission' => 'cotizaciones.bandeja.ver', 'parent' => 'quotations', 'label' => 'Bandeja de RFQ', 'description' => 'Bandeja de solicitudes recibidas.', 'category' => 'Compras'],
        'purchase_orders' => ['permission' => 'ordenes_compra.ver', 'label' => 'Órdenes de compra', 'description' => 'Consulta y operación de órdenes de compra.', 'category' => 'Compras'],
        'receptions' => ['permission' => 'recepciones.ver', 'label' => 'Recepciones', 'description' => 'Acceso al módulo de recepciones.', 'category' => 'Compras'],
        'products_services' => ['permission' => 'productos_servicios.ver', 'legacy_permissions' => ['productos.ver'], 'label' => 'Productos y servicios', 'description' => 'Consulta del catálogo de productos y servicios.', 'category' => 'Catálogo'],
        'budget_control' => ['permission' => 'control_presupuestal.ver', 'legacy_permissions' => ['catalogo_cuentas.ver'], 'label' => 'Control presupuestal', 'description' => 'Consulta y operación presupuestal.', 'category' => 'Presupuesto'],
        'budget_categories' => ['permission' => 'presupuesto.categorias.ver', 'parent' => 'budget_control', 'label' => 'Categorías de gasto', 'description' => 'Vista de categorías presupuestales.', 'category' => 'Presupuesto'],
        'budget_cost_centers' => ['permission' => 'presupuesto.centros_costo.ver', 'parent' => 'budget_control', 'label' => 'Centros de costo', 'description' => 'Vista de centros de costo.', 'category' => 'Presupuesto'],
        'budget_expense_sheets' => ['permission' => 'presupuesto.cedulas_gasto.ver', 'parent' => 'budget_control', 'label' => 'Cédulas de gasto', 'description' => 'Vista de cédulas de gasto.', 'category' => 'Presupuesto'],
        'budget_accounts' => ['permission' => 'presupuesto.cuentas.ver', 'parent' => 'budget_control', 'label' => 'Cuentas presupuestales', 'description' => 'Vista de cuentas presupuestales.', 'category' => 'Presupuesto'],
        'budget_annual' => ['permission' => 'presupuesto.anual.ver', 'parent' => 'budget_control', 'label' => 'Presupuestos anuales', 'description' => 'Vista de presupuestos anuales.', 'category' => 'Presupuesto'],
        'budget_monthly' => ['permission' => 'presupuesto.distribucion_mensual.ver', 'parent' => 'budget_control', 'label' => 'Distribución mensual', 'description' => 'Vista de distribución mensual.', 'category' => 'Presupuesto'],
        'budget_movements' => ['permission' => 'presupuesto.movimientos.ver', 'parent' => 'budget_control', 'label' => 'Movimientos presupuestales', 'description' => 'Vista de movimientos presupuestales.', 'category' => 'Presupuesto'],
        'budget_profiles' => ['permission' => 'perfiles_presupuestales.ver', 'legacy_permissions' => ['perfiles_presupuestales.ver'], 'label' => 'Perfiles presupuestales', 'description' => 'Acceso a perfiles y asignaciones presupuestales.', 'category' => 'Presupuesto'],
        'payments_billing' => ['permission' => 'pagos_facturacion.ver', 'label' => 'Pagos y facturación', 'description' => 'Acceso a pagos, facturas y provisiones.', 'category' => 'Finanzas'],
        'billing_invoices' => ['permission' => 'pagos.facturas.ver', 'parent' => 'payments_billing', 'label' => 'Facturas', 'description' => 'Vista de facturas.', 'category' => 'Finanzas'],
        'billing_provisions' => ['permission' => 'pagos.provisiones.ver', 'parent' => 'payments_billing', 'label' => 'Provisiones', 'description' => 'Vista de provisiones.', 'category' => 'Finanzas'],
        'document_review' => ['permission' => 'revision_documental.ver', 'label' => 'Revisión documental', 'description' => 'Consulta y revisión documental de proveedores.', 'category' => 'Proveedores'],
        'document_review_queue' => ['permission' => 'revision_documental.bandeja.ver', 'parent' => 'document_review', 'label' => 'Bandeja de revisión documental', 'description' => 'Bandeja de documentos por revisar.', 'category' => 'Proveedores'],
        'supplier_admin' => ['permission' => 'proveedores.administracion.ver', 'parent' => 'document_review', 'label' => 'Gestión de proveedores', 'description' => 'Vista de gestión de proveedores.', 'category' => 'Proveedores'],
        'supplier_compliance' => ['permission' => 'proveedores.cumplimiento.ver', 'parent' => 'document_review', 'label' => 'Cumplimiento de proveedores', 'description' => 'Vista de cumplimiento y registros de proveedores.', 'category' => 'Proveedores'],
        'supplier_document_catalog' => ['permission' => 'catalogo_documental.ver', 'label' => 'Catálogo documental', 'description' => 'Administración del catálogo documental.', 'category' => 'Proveedores'],
        'communicator' => ['permission' => 'comunicados.ver', 'label' => 'Comunicados', 'description' => 'Consulta y publicación de comunicados.', 'category' => 'Administración'],
        'staff_users' => ['permission' => 'usuarios_staff.ver', 'legacy_permissions' => ['usuarios.ver'], 'label' => 'Usuarios Staff', 'description' => 'Administración de usuarios internos.', 'category' => 'Administración'],
        'staff_users_main' => ['permission' => 'usuarios_staff.principal.ver', 'parent' => 'staff_users', 'label' => 'Listado de usuarios Staff', 'description' => 'Vista principal de usuarios Staff.', 'category' => 'Administración'],
        'employees' => ['permission' => 'empleados.ver', 'legacy_permissions' => ['usuarios.ver'], 'label' => 'Empleados', 'description' => 'Consulta y administración de empleados.', 'category' => 'Administración'],
        'catalogs_config' => ['permission' => 'catalogos.ver', 'legacy_permissions' => ['departamentos.administrar'], 'label' => 'Catálogos', 'description' => 'Grupo de catálogos maestros del portal.', 'category' => 'Administración', 'hidden' => true],
        'catalog_companies' => ['permission' => 'catalogos.empresas.ver', 'label' => 'Empresas', 'description' => 'Consulta del catálogo de empresas.', 'category' => 'Catálogos'],
        'catalog_stations' => ['permission' => 'catalogos.estaciones.ver', 'label' => 'Estaciones', 'description' => 'Consulta del catálogo de estaciones.', 'category' => 'Catálogos'],
        'catalog_departments' => ['permission' => 'catalogos.departamentos.ver', 'label' => 'Departamentos', 'description' => 'Consulta del catálogo de departamentos.', 'category' => 'Catálogos'],
        'catalog_receiving_locations' => ['permission' => 'catalogos.ubicaciones_recepcion.ver', 'label' => 'Ubicaciones de recepción', 'description' => 'Consulta del catálogo de ubicaciones de recepción.', 'category' => 'Catálogos'],
        'catalog_tax_codes' => ['permission' => 'catalogos.codigos_impuesto.ver', 'label' => 'Catálogo de impuestos', 'description' => 'Consulta del catálogo de códigos de impuesto.', 'category' => 'Catálogos'],
        'catalog_tax_groups' => ['permission' => 'catalogos.grupos_impuesto.ver', 'label' => 'Grupos de impuestos', 'description' => 'Consulta del catálogo de grupos de impuestos.', 'category' => 'Catálogos'],
        'catalog_ledger_accounts' => ['permission' => 'catalogos.cuentas_contables.ver', 'label' => 'Cuentas contables', 'description' => 'Consulta del catálogo de cuentas contables.', 'category' => 'Catálogos'],
        'catalog_authorizer_roles' => ['permission' => 'catalogos.roles_autorizadores.ver', 'label' => 'Roles autorizadores', 'description' => 'Consulta del catálogo de roles autorizadores.', 'category' => 'Catálogos'],
        'catalog_delegations' => ['permission' => 'catalogos.delegaciones.ver', 'label' => 'Delegaciones activas', 'description' => 'Consulta de delegaciones activas.', 'category' => 'Catálogos'],
        'catalog_approval_levels' => ['permission' => 'catalogos.niveles_autorizacion.ver', 'label' => 'Niveles de autorización', 'description' => 'Consulta del catálogo de niveles de autorización.', 'category' => 'Catálogos'],
        'catalog_sat_withholdings' => ['permission' => 'catalogos.retenciones_sat.ver', 'label' => 'Retenciones SAT', 'description' => 'Consulta del catálogo de retenciones SAT.', 'category' => 'Catálogos'],
        'reported_incidents' => ['permission' => 'incidentes.ver', 'label' => 'Incidentes', 'description' => 'Consulta y gestión de incidentes reportados.', 'category' => 'Administración'],
        'tools_cfdi' => ['permission' => 'herramientas.cfdi.ver', 'label' => 'Generador CFDI', 'description' => 'Acceso al generador de CFDI.', 'category' => 'Herramientas'],
        'user_sessions' => ['permission' => 'sesiones_usuarios.ver', 'label' => 'Sesiones de usuarios', 'description' => 'Consulta de sesiones de usuarios.', 'category' => 'Administración'],
        'monitoring_alerts' => ['permission' => 'monitoreo_alertas.ver', 'label' => 'Monitoreo de alertas', 'description' => 'Consulta del centro de alertas.', 'category' => 'Monitoreo'],
        'monitoring_operations' => ['permission' => 'monitoreo_operaciones.ver', 'label' => 'Monitoreo de operación', 'description' => 'Consulta del monitoreo de compras.', 'category' => 'Monitoreo'],
        'monitoring_budget' => ['permission' => 'monitoreo_presupuesto.ver', 'label' => 'Monitoreo presupuestal', 'description' => 'Consulta del monitoreo de presupuesto.', 'category' => 'Monitoreo'],
        'monitoring_suppliers' => ['permission' => 'monitoreo_proveedores.ver', 'label' => 'Monitoreo de proveedores', 'description' => 'Consulta del monitoreo de proveedores.', 'category' => 'Monitoreo'],
        'monitoring_security' => ['permission' => 'monitoreo_seguridad.ver', 'label' => 'Monitoreo de seguridad', 'description' => 'Consulta del monitoreo de seguridad.', 'category' => 'Monitoreo'],
        'supplier_documents' => ['permission' => 'documentos_proveedor.ver', 'label' => 'Documentos de proveedor', 'description' => 'Acceso del proveedor a sus documentos.', 'category' => 'Proveedores'],
        'supplier_communicator' => ['permission' => 'comunicador_proveedor.ver', 'label' => 'Comunicador de proveedor', 'description' => 'Acceso del proveedor a comunicados.', 'category' => 'Proveedores'],
        'supplier_billing' => ['permission' => 'facturacion_proveedor.ver', 'label' => 'Facturación de proveedor', 'description' => 'Acceso del proveedor a facturación.', 'category' => 'Proveedores'],
    ],
];
