@php
    $movement = $budgetMovement ?? null;
    $origin = $movement?->originDetails()->first();
    $destination = $movement?->destinationDetails()->first();
    $adjustment = $movement?->adjustmentDetails()->first();
@endphp
<form method="POST" action="{{ $movement ? route('budget_movements.update', $movement) : route('budget_movements.store') }}" id="budgetMovementForm">
    @csrf @if($movement) @method('PUT') @endif
    <section class="bm-form-section"><span class="bm-kicker">1. Tipo de solicitud</span><h2>¿Qué necesitas hacer?</h2>
        <div class="row g-3"><div class="col-md-4"><label class="form-label">Movimiento</label><select name="movement_type" id="movement_type" class="form-select" required><option value="AMPLIACION" @selected(old('movement_type',$movement?->movement_type)==='AMPLIACION')>Ampliar presupuesto</option><option value="TRANSFERENCIA" @selected(old('movement_type',$movement?->movement_type)==='TRANSFERENCIA')>Transferir presupuesto</option><option value="REDUCCION" @selected(old('movement_type',$movement?->movement_type)==='REDUCCION')>Reducir presupuesto</option></select></div><div class="col-md-4"><label class="form-label">Año fiscal</label><input class="form-control" type="number" name="fiscal_year" value="{{ old('fiscal_year',$movement?->fiscal_year ?? $currentYear) }}" required></div><div class="col-md-4"><label class="form-label">Fecha</label><input class="form-control" type="date" name="movement_date" value="{{ old('movement_date',optional($movement?->movement_date)->format('Y-m-d') ?? now()->format('Y-m-d')) }}" required></div></div>
    </section>
    <section class="bm-form-section js-single"><span class="bm-kicker">2. Centro a afectar</span><h2>Tu centro de costo</h2>
        <div class="row g-3"><div class="col-md-6"><label class="form-label">Centro de costo</label><select name="cost_center_id" class="form-select">@foreach($ownedCostCenters as $center)<option value="{{ $center->id }}" @selected(old('cost_center_id',$adjustment?->cost_center_id)==$center->id)>{{ $center->code }} · {{ $center->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Mes</label><input class="form-control" type="number" min="1" max="12" name="month" value="{{ old('month',$adjustment?->month) }}"></div><div class="col-md-3"><label class="form-label">Monto</label><input class="form-control" type="number" step="0.01" min="0.01" name="total_amount" value="{{ old('total_amount',$movement?->total_amount) }}" required></div></div>
        <div class="row g-3 mt-0"><div class="col-md-6"><label class="form-label">Cuenta</label><select name="expense_category_id" class="form-select"><option value="">Selecciona</option>@foreach($expenseCategories as $category)<option value="{{ $category->id }}" @selected(old('expense_category_id',$adjustment?->expense_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Subcuenta</label><select name="budget_cedula_id" class="form-select"><option value="">Selecciona</option>@foreach($budgetCedulas as $cedula)<option value="{{ $cedula->id }}" @selected(old('budget_cedula_id',$adjustment?->budget_cedula_id)==$cedula->id)>{{ $cedula->name }}</option>@endforeach</select></div></div>
    </section>
    <section class="bm-form-section js-transfer d-none"><span class="bm-kicker">2. Transferencia</span><h2>Indica de dónde sale y a dónde llega</h2>
        @foreach(['origin' => ['Origen', $originCostCenters, $origin], 'destination' => ['Destino', $ownedCostCenters, $destination]] as $prefix => [$label,$centers,$detail])
        <div class="row g-3 {{ $prefix==='destination'?'mt-1':'' }}"><div class="col-12"><strong>{{ $label }}</strong>@if($prefix==='destination') <small class="text-muted">Solo puedes seleccionar centros de los que eres responsable.</small>@endif</div><div class="col-md-5"><label class="form-label">Centro de costo</label><select name="{{ $prefix }}_cost_center_id" class="form-select"><option value="">Selecciona</option>@foreach($centers as $center)<option value="{{ $center->id }}" @selected(old($prefix.'_cost_center_id',$detail?->cost_center_id)==$center->id)>{{ $center->code }} · {{ $center->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Mes</label><input type="number" min="1" max="12" class="form-control" name="{{ $prefix }}_month" value="{{ old($prefix.'_month',$detail?->month) }}"></div><div class="col-md-5"><label class="form-label">Cuenta</label><select name="{{ $prefix }}_expense_category_id" class="form-select"><option value="">Selecciona</option>@foreach($expenseCategories as $category)<option value="{{ $category->id }}" @selected(old($prefix.'_expense_category_id',$detail?->expense_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Subcuenta</label><select name="{{ $prefix }}_budget_cedula_id" class="form-select"><option value="">Selecciona</option>@foreach($budgetCedulas as $cedula)<option value="{{ $cedula->id }}" @selected(old($prefix.'_budget_cedula_id',$detail?->budget_cedula_id)==$cedula->id)>{{ $cedula->name }}</option>@endforeach</select></div>@if($prefix==='destination')<div class="col-md-6"><label class="form-label">Monto a transferir</label><input class="form-control" type="number" step="0.01" min="0.01" name="total_amount" value="{{ old('total_amount',$movement?->total_amount) }}"></div>@endif</div>
        @endforeach
    </section>
    <section class="bm-form-section"><span class="bm-kicker">3. Justificación</span><h2>Explica la necesidad del movimiento</h2><textarea name="justification" class="form-control" rows="4" minlength="10" required>{{ old('justification',$movement?->justification) }}</textarea><small class="text-muted">La justificación será visible para los responsables y Dirección General.</small></section>
    @if($errors->any())<div class="alert alert-danger"><strong>Revisa los datos capturados.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="d-flex justify-content-end gap-2"><a class="btn btn-light" href="{{ route('budget_movements.index') }}">Cancelar</a><button class="btn btn-primary bm-save" type="submit">{{ $movement ? 'Guardar y reenviar' : 'Enviar solicitud' }}</button></div>
</form>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.querySelector('#movement_type'),single=document.querySelector('.js-single'),transfer=document.querySelector('.js-transfer');const toggle=()=>{const isTransfer=type.value==='TRANSFERENCIA';single.classList.toggle('d-none',isTransfer);transfer.classList.toggle('d-none',!isTransfer)};type.addEventListener('change',toggle);toggle();document.querySelector('#budgetMovementForm').addEventListener('submit',e=>{const b=e.submitter;b.disabled=true;b.textContent='Enviando…'})})</script>@endpush
