@extends('layouts.zircos')
@section('title','Detalle del movimiento')
@section('content')
@include('budget_movements.workflow._styles')
@php($labels=['PENDIENTE_ORIGEN'=>'Esperando validación del origen','PENDIENTE_DIRECCION'=>'Esperando Dirección General','DEVUELTO'=>'Devuelto para corrección','APROBADO'=>'Aprobado','RECHAZADO'=>'Rechazado'])
<div class="bm-shell"><header class="bm-hero"><div><span class="bm-kicker">Solicitud #{{ $budgetMovement->id }}</span><h1>{{ ucfirst(strtolower($budgetMovement->movement_type)) }} por ${{ number_format($budgetMovement->total_amount,2) }}</h1><p>{{ $labels[$budgetMovement->status] ?? $budgetMovement->status }}</p><div class="bm-flow"><span class="{{ $budgetMovement->isTransfer() && $budgetMovement->status==='PENDIENTE_ORIGEN'?'is-current':'' }}">Validación origen</span><span class="{{ $budgetMovement->status==='PENDIENTE_DIRECCION'?'is-current':'' }}">Dirección General</span><span class="{{ $budgetMovement->isApproved()?'is-current':'' }}">Aplicado</span></div></div><a class="btn btn-light" href="{{ route('budget_movements.index') }}">Volver</a></header>
<section class="bm-card"><div class="bm-detail-grid"><div class="bm-fact"><span>Solicitante</span><strong>{{ $budgetMovement->creator?->name }}</strong></div><div class="bm-fact"><span>Fecha</span><strong>{{ $budgetMovement->movement_date->format('d/m/Y') }}</strong></div><div class="bm-fact"><span>Año fiscal</span><strong>{{ $budgetMovement->fiscal_year }}</strong></div><div class="bm-fact"><span>Aprobador final</span><strong>{{ $budgetMovement->approver?->name ?? 'Pendiente' }}</strong></div></div><div class="mt-3"><span class="bm-kicker">Justificación</span><p class="mb-0">{{ $budgetMovement->justification }}</p></div></section>
<section class="bm-card"><span class="bm-kicker">Partidas afectadas</span><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Tipo</th><th>Centro</th><th>Mes</th><th>Cuenta / subcuenta</th><th>Monto</th></tr></thead><tbody>@foreach($budgetMovement->details as $detail)<tr><td>{{ $detail->detail_type }}</td><td>{{ $detail->costCenter?->name }}</td><td>{{ $detail->month_name }}</td><td>{{ $detail->expenseCategory?->name }}<small class="d-block text-muted">{{ $detail->budgetCedula?->name }}</small></td><td class="{{ $detail->amount < 0?'text-danger':'text-success' }}">${{ number_format($detail->amount,2) }}</td></tr>@endforeach</tbody></table></div></section>
@if($budgetMovement->created_by===auth()->id() && $budgetMovement->isReturned())<section class="bm-card"><a class="btn btn-primary" href="{{ route('budget_movements.edit',$budgetMovement) }}">Corregir y reenviar</a></section>@endif
@if($canOriginApprove)<section class="bm-card"><span class="bm-kicker">Acción requerida</span><h2 class="h5">Valida la salida de presupuesto de tu centro</h2><div class="d-flex gap-2"><form method="POST" action="{{ route('budget_movements.origin-approve',$budgetMovement) }}">@csrf<button class="btn btn-success">Aceptar transferencia</button></form><details><summary class="btn btn-outline-danger">Devolver para corrección</summary><form method="POST" action="{{ route('budget_movements.return',$budgetMovement) }}" class="mt-2">@csrf<textarea required minlength="10" class="form-control mb-2" name="comments" placeholder="Explica qué debe corregirse"></textarea><button class="btn btn-danger">Devolver</button></form></details></div></section>@endif
@if($canExecutiveApprove)<section class="bm-card"><span class="bm-kicker">Aprobación ejecutiva</span><h2 class="h5">Autoriza y aplica el movimiento</h2><p class="text-muted">Al aprobar se actualizará el presupuesto de forma irreversible.</p><div class="d-flex gap-2"><form method="POST" action="{{ route('budget_movements.approve',$budgetMovement) }}">@csrf<button class="btn btn-success">Aprobar y aplicar</button></form><details><summary class="btn btn-outline-danger">Rechazar</summary><form method="POST" action="{{ route('budget_movements.reject',$budgetMovement) }}" class="mt-2">@csrf<textarea required minlength="10" class="form-control mb-2" name="comments" placeholder="Motivo obligatorio del rechazo"></textarea><button class="btn btn-danger">Confirmar rechazo</button></form></details></div></section>@endif
<section class="bm-card"><span class="bm-kicker">Trazabilidad</span><div class="bm-timeline">@forelse($budgetMovement->decisions->sortBy('created_at') as $decision)<div class="bm-timeline-item"><strong>{{ $decision->action }} · {{ $decision->stage }}</strong><small class="d-block text-muted">{{ $decision->actor?->name }} · {{ $decision->created_at->format('d/m/Y H:i') }}</small>@if($decision->comments)<p class="mb-0">{{ $decision->comments }}</p>@endif</div>@empty<div class="text-muted">No hay decisiones registradas.</div>@endforelse</div></section></div>
@endsection
