@extends('layouts.zircos')
@section('title', $type->exists ? 'Editar documento' : 'Nuevo documento')
@section('page.title', $type->exists ? 'Editar documento' : 'Nuevo documento')
@section('content')
<form method="POST" action="{{ $type->exists ? route('supplier-document-types.update', $type) : route('supplier-document-types.store') }}"><div class="card"><div class="card-body">
@csrf @if($type->exists) @method('PUT') @endif
<div class="row g-3"><div class="col-md-4"><label class="form-label">Clave</label><input class="form-control" name="code" value="{{ old('code', $type->code) }}" required></div><div class="col-md-8"><label class="form-label">Nombre</label><input class="form-control" name="name" value="{{ old('name', $type->name) }}" required></div><div class="col-12"><label class="form-label">Descripción</label><textarea class="form-control" name="description" rows="2">{{ old('description', $type->description) }}</textarea></div>
<div class="col-md-4"><label class="form-label">Modalidad</label><select class="form-select" name="renewal_mode" id="renewalMode"><option value="once" @selected(old('renewal_mode', $type->renewal_mode ?: 'once') === 'once')>Una sola vez</option><option value="periodic" @selected(old('renewal_mode', $type->renewal_mode) === 'periodic')>Periódico</option></select></div><div class="col-md-4"><label class="form-label">Cada cuántos días</label><input class="form-control" type="number" min="1" name="renewal_interval_days" value="{{ old('renewal_interval_days', $type->renewal_interval_days) }}"></div><div class="col-md-4"><label class="form-label">Origen de vigencia</label><select class="form-select" name="validity_source"><option value="manual" @selected(old('validity_source', $type->validity_source ?: 'manual') === 'manual')>Confirmada por revisor</option><option value="qr" @selected(old('validity_source', $type->validity_source) === 'qr')>Extraída desde QR</option></select></div>
<div class="col-12"><div class="d-flex flex-wrap gap-4">@foreach(['is_active'=>'Activo','is_required'=>'Obligatorio','applies_to_physical'=>'Persona física','applies_to_legal'=>'Persona moral','requires_repse'=>'Solo REPSE'] as $field=>$label)<label class="form-check"><input class="form-check-input" type="checkbox" name="{{ $field }}" value="1" @checked(old($field, $type->{$field} ?? ($field !== 'requires_repse')))><span class="form-check-label">{{ $label }}</span></label>@endforeach</div></div></div>
</div><div class="card-footer d-flex justify-content-end gap-2"><a class="btn btn-light" href="{{ route('supplier-document-types.index') }}">Cancelar</a><button class="btn btn-primary" type="submit">Guardar</button></div></div></form>
@endsection
