@extends('layouts.zircos')

@section('title', 'Alertas presupuestales RP-03')
@section('page.title', 'Alertas presupuestales')

@section('content')
<div class="card border-0 shadow-sm mb-3"><div class="card-body d-flex flex-wrap align-items-center gap-3"><div class="flex-grow-1"><span class="text-primary small fw-bold">PRESUPUESTO · RP-03</span><h4 class="mb-1">Alertas de agotamiento, sobregiro y excepciones</h4><p class="mb-0 text-muted">Disponible negativo conserva el sobregiro; el ritmo aparece después de tres meses cerrados con historial.</p></div><a class="btn btn-outline-primary" href="{{ route('budget-alert-reports.export', ['format'=>'csv'] + request()->query()) }}">CSV</a><a class="btn btn-primary" href="{{ route('budget-alert-reports.export', ['format'=>'xlsx'] + request()->query()) }}">Descargar Excel</a></div></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><h5>Filtros</h5><div class="row g-3"><div class="col-md-3"><label class="form-label">Ejercicio</label><input class="form-control" id="year" type="number" value="{{ request('year', now()->year) }}"></div><div class="col-md-3"><label class="form-label">Empresa</label><select class="form-select" id="company_id"><option value="">Todas</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Centro</label><select class="form-select" id="cost_center_id"><option value="">Todos</option>@foreach($centers as $center)<option value="{{ $center->id }}">{{ $center->company?->name }} · {{ $center->code }} · {{ $center->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Estado de excepción</label><select class="form-select" id="status"><option value="">Todos</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option></select></div><div class="col-12 text-end"><button class="btn btn-light" id="clear">Limpiar</button><button class="btn btn-primary" id="apply">Aplicar filtros</button></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white"><ul class="nav nav-tabs card-header-tabs"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#risk">Renglones en riesgo</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#exceptions">Excepciones</button></li></ul></div><div class="tab-content"><div class="tab-pane fade show active p-3" id="risk"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Empresa / centro</th><th>Renglón</th><th>Periodo</th><th>Asignado</th><th>Ejercido</th><th>Disponible</th><th>%</th><th>Ritmo / proyección</th><th>Documentos comprometidos</th></tr></thead><tbody id="risk-rows"><tr><td colspan="9" class="text-center text-muted">Cargando…</td></tr></tbody></table></div></div><div class="tab-pane fade p-3" id="exceptions"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Documento / partida</th><th>Importe</th><th>Excedente</th><th>Motivo</th><th>Solicitó / autorizó</th><th>Estado</th><th>Decisión</th></tr></thead><tbody id="exception-rows"><tr><td colspan="7" class="text-center text-muted">Cargando…</td></tr></tbody></table></div></div></div></div>
@endsection

@push('scripts')
<script>
(() => {
 const dataUrl = @json(route('budget-alert-reports.data'));
 const decideUrl = @json(url('/reportes/presupuesto/alertas/excepciones'));
 const canDecide = @json(auth()->user()->hasRole('general_director'));
 const money = n => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n||0));
 async function load(){
   const params=new URLSearchParams(); ['year','company_id','cost_center_id','status'].forEach(id=>{const v=document.getElementById(id).value;if(v)params.set(id,v)});
   const res=await fetch(dataUrl+'?'+params,{headers:{'Accept':'application/json'}}); if(!res.ok)return;
   const data=await res.json();
   document.getElementById('risk-rows').innerHTML=data.lines.length?data.lines.map(r=>`<tr><td>${r.company||'—'}<br><span class="text-muted">${r.cost_center||'—'} · ${r.responsible||'Sin responsable'}</span></td><td>${r.account||'—'} / ${r.subaccount||'—'}</td><td>${r.year}-${String(r.month).padStart(2,'0')}</td><td>${money(r.assigned)}</td><td>${money(r.consumed_total)}</td><td class="${r.available<0?'text-danger fw-bold':''}">${money(r.available)}</td><td>${r.consumed_pct===null?'—':r.consumed_pct+'%'}</td><td>${r.burn_rate_3m===null?'<span class="text-muted">Sin historial suficiente</span>':money(r.burn_rate_3m)+' / mes<br>'+(r.projected_exhaustion||'Sin agotamiento proyectado')}</td></tr>`).join(''):'<tr><td colspan="9" class="text-center text-muted">No hay renglones en riesgo con estos filtros.</td></tr>';
   const rows=data.exceptions.data||[];
   document.getElementById('exception-rows').innerHTML=rows.length?rows.map(e=>`<tr><td>${e.document_type} #${e.document_id}<br><span class="text-muted">Partida ${e.document_line_id}</span></td><td>${money(e.line_amount)}</td><td>${money(e.approved_excess??e.requested_excess)}</td><td>${e.reason}</td><td>${e.requester?.name||'—'}<br>${e.decider?.name||'Pendiente'}</td><td>${e.status}</td><td>${canDecide&&e.status==='PENDING'?`<button class="btn btn-sm btn-success" onclick="decide(${e.id},'APPROVED')">Aprobar</button> <button class="btn btn-sm btn-outline-danger" onclick="decide(${e.id},'REJECTED')">Rechazar</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="7" class="text-center text-muted">No hay excepciones con estos filtros.</td></tr>';
 }
 window.decide=async(id,decision)=>{const comment=prompt('Comentario de Dirección General (opcional):')||'';const r=await fetch(`${decideUrl}/${id}/decision`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':@json(csrf_token()),'Accept':'application/json'},body:JSON.stringify({decision,comment})});if(!r.ok){alert('No se pudo guardar la decisión.');return}load()};
 document.getElementById('apply').addEventListener('click',load); document.getElementById('clear').addEventListener('click',()=>{['company_id','cost_center_id','status'].forEach(id=>document.getElementById(id).value='');document.getElementById('year').value='';load()}); load();
})();
</script>
@endpush
